DATA LIST FILE='C:\COUNTRIES\RW70\RWKR70FL.DAT' RECORDS=1
  /
  CASEID      1-15   (A)
  MIDX       16-16  
  V000       17-19   (A)
  V001       20-27  
  V002       28-31  
  V003       32-34  
  V004       35-38  
  V005       39-46  
  V006       47-48  
  V007       49-52  
  V008       53-56  
  V009       57-58  
  V010       59-62  
  V011       63-66  
  V012       67-68  
  V013       69-69  
  V014       70-70  
  V015       71-71  
  V016       72-73  
  V017       74-77  
  V018       78-79  
  V019       80-81  
  V019A      82-82  
  V020       83-83  
  V021       84-87  
  V022       88-91  
  V023       92-93  
  V024       94-95  
  V025       96-96  
  V026       97-97  
  V027       98-98  
  V028       99-101 
  V029      102-103 
  V030      104-106 
  V031      107-109 
  V032      110-111 
  V034      112-113 
  V040      114-117 
  V042      118-118 
  V044      119-119 
  V101      120-121 
  V102      122-122 
  V103      123-123 
  V104      124-125 
  V105      126-126 
  V106      127-127 
  V107      128-129 
  V113      130-131 
  V115      132-134 
  V116      135-136 
  V119      137-137 
  V120      138-138 
  V121      139-139 
  V122      140-140 
  V123      141-141 
  V124      142-142 
  V125      143-143 
  V127      144-145 
  V128      146-147 
  V129      148-149 
  V130      150-151 
  V131      152-154 
  V133      155-156 
  V134      157-157 
  V135      158-158 
  V136      159-160 
  V137      161-162 
  V138      163-164 
  V139      165-166 
  V140      167-167 
  V141      168-168 
  V149      169-169 
  V150      170-171 
  V151      172-172 
  V152      173-174 
  V153      175-175 
  AWFACTT   176-180 
  AWFACTU   181-185 
  AWFACTR   186-190 
  AWFACTE   191-195 
  AWFACTW   196-200 
  V155      201-201 
  V156      202-202 
  V157      203-203 
  V158      204-204 
  V159      205-205 
  V160      206-206 
  V161      207-208 
  V166      209-211 
  V167      212-213 
  V168      214-214 
  V190      215-215 
  V191      216-223 
  ML101     224-224 
  V201      225-226 
  V202      227-228 
  V203      229-230 
  V204      231-232 
  V205      233-234 
  V206      235-236 
  V207      237-238 
  V208      239-239 
  V209      240-240 
  V210      241-241 
  V211      242-245 
  V212      246-247 
  V213      248-248 
  V214      249-250 
  V215      251-253 
  V216      254-254 
  V217      255-255 
  V218      256-257 
  V219      258-259 
  V220      260-260 
  V221      261-263 
  V222      264-266 
  V223      267-267 
  V224      268-269 
  V225      270-270 
  V226      271-273 
  V227      274-274 
  V228      275-275 
  V229      276-277 
  V230      278-281 
  V231      282-285 
  V232      286-286 
  V233      287-288 
  V234      289-289 
  V235      290-291 
  V237      292-292 
  V238      293-293 
  V239      294-294 
  V240      295-296 
  V241      297-300 
  V242      301-304 
  V243      305-305 
  V310      306-307 
  V311      308-308 
  V312      309-310 
  V313      311-311 
  V315      312-313 
  V316      314-317 
  V317      318-321 
  V318      322-322 
  V319      323-323 
  V320      324-324 
  V321      325-325 
  V322      326-326 
  V323      327-328 
  V323A     329-330 
  V325A     331-337 
  V326      338-339 
  V327      340-340 
  V337      341-343 
  V359      344-345 
  V360      346-347 
  V361      348-348 
  V362      349-349 
  V363      350-351 
  V364      352-352 
  V367      353-353 
  V372      354-354 
  V372A     355-355 
  V375A     356-357 
  V376      358-359 
  V376A     360-360 
  V379      361-362 
  V380      363-363 
  V384A     364-364 
  V384B     365-365 
  V384C     366-366 
  V393      367-367 
  V394      368-368 
  V395      369-369 
  V3A00A    370-370 
  V3A00B    371-371 
  V3A00C    372-372 
  V3A00D    373-373 
  V3A00E    374-374 
  V3A00F    375-375 
  V3A00G    376-376 
  V3A00H    377-377 
  V3A00I    378-378 
  V3A00J    379-379 
  V3A00K    380-380 
  V3A00L    381-381 
  V3A00M    382-382 
  V3A00N    383-383 
  V3A00O    384-384 
  V3A00P    385-385 
  V3A00Q    386-386 
  V3A00R    387-387 
  V3A00S    388-388 
  V3A00T    389-389 
  V3A00U    390-390 
  V3A00V    391-391 
  V3A00W    392-392 
  V3A00X    393-393 
  V3A00Y    394-394 
  V3A00Z    395-395 
  V3A01     396-396 
  V3A02     397-397 
  V3A03     398-398 
  V3A04     399-399 
  V3A05     400-400 
  V3A06     401-401 
  V3A07     402-403 
  V3A08A    404-404 
  V3A08B    405-405 
  V3A08C    406-406 
  V3A08D    407-407 
  V3A08E    408-408 
  V3A08F    409-409 
  V3A08G    410-410 
  V3A08H    411-411 
  V3A08I    412-412 
  V3A08J    413-413 
  V3A08K    414-414 
  V3A08L    415-415 
  V3A08M    416-416 
  V3A08N    417-417 
  V3A08O    418-418 
  V3A08P    419-419 
  V3A08Q    420-420 
  V3A08R    421-421 
  V3A08S    422-422 
  V3A08T    423-423 
  V3A08U    424-424 
  V3A08V    425-425 
  V3A08W    426-426 
  V3A08AA   427-427 
  V3A08AB   428-428 
  V3A08AC   429-429 
  V3A08AD   430-430 
  V3A08X    431-431 
  V3A08Z    432-432 
  V3A09A    433-435 
  V3A09B    436-438 
  V401      439-439 
  V404      440-440 
  V405      441-441 
  V406      442-442 
  V407      443-444 
  V408      445-446 
  V409      447-447 
  V409A     448-448 
  V410      449-449 
  V410A     450-450 
  V411      451-451 
  V411A     452-452 
  V412      453-453 
  V412A     454-454 
  V412B     455-455 
  V412C     456-456 
  V413      457-457 
  V413A     458-458 
  V413B     459-459 
  V413C     460-460 
  V413D     461-461 
  V414A     462-462 
  V414B     463-463 
  V414C     464-464 
  V414D     465-465 
  V414E     466-466 
  V414F     467-467 
  V414G     468-468 
  V414H     469-469 
  V414I     470-470 
  V414J     471-471 
  V414K     472-472 
  V414L     473-473 
  V414M     474-474 
  V414N     475-475 
  V414O     476-476 
  V414P     477-477 
  V414Q     478-478 
  V414R     479-479 
  V414S     480-480 
  V414T     481-481 
  V414U     482-482 
  V414V     483-483 
  V414W     484-484 
  V415      485-485 
  V416      486-486 
  V417      487-487 
  V418      488-488 
  V419      489-489 
  V420      490-492 
  V421      493-495 
  V426      496-498 
  V437      499-502 
  V438      503-506 
  V439      507-510 
  V440      511-514 
  V441      515-519 
  V442      520-524 
  V443      525-529 
  V444      530-534 
  V444A     535-538 
  V445      539-542 
  V446      543-546 
  V447      547-547 
  V447A     548-549 
  V452A     550-550 
  V452B     551-552 
  V452C     553-553 
  V453      554-556 
  V454      557-557 
  V455      558-558 
  V456      559-561 
  V457      562-562 
  V458      563-563 
  V459      564-564 
  V460      565-565 
  V461      566-566 
  V462      567-567 
  V463A     568-568 
  V463B     569-569 
  V463C     570-570 
  V463D     571-571 
  V463E     572-572 
  V463F     573-573 
  V463G     574-574 
  V463X     575-575 
  V463Z     576-576 
  V464      577-578 
  V465      579-580 
  V466      581-581 
  V467A     582-582 
  V467B     583-583 
  V467C     584-584 
  V467D     585-585 
  V467E     586-586 
  V467F     587-587 
  V467G     588-588 
  V467H     589-589 
  V467I     590-590 
  V467J     591-591 
  V467K     592-592 
  V467L     593-593 
  V467M     594-594 
  V468      595-595 
  V469E     596-596 
  V469F     597-597 
  V469X     598-598 
  V471A     599-599 
  V471B     600-600 
  V471C     601-601 
  V471D     602-602 
  V471E     603-603 
  V471F     604-604 
  V471G     605-605 
  V472A     606-606 
  V472B     607-607 
  V472C     608-608 
  V472D     609-609 
  V472E     610-610 
  V472F     611-611 
  V472G     612-612 
  V472H     613-613 
  V472I     614-614 
  V472J     615-615 
  V472K     616-616 
  V472L     617-617 
  V472M     618-618 
  V472N     619-619 
  V472O     620-620 
  V472P     621-621 
  V472Q     622-622 
  V472R     623-623 
  V472S     624-624 
  V472T     625-625 
  V472U     626-626 
  V473A     627-627 
  V473B     628-628 
  V474      629-629 
  V474A     630-630 
  V474B     631-631 
  V474C     632-632 
  V474D     633-633 
  V474E     634-634 
  V474F     635-635 
  V474G     636-636 
  V474H     637-637 
  V474I     638-638 
  V474J     639-639 
  V474K     640-640 
  V474X     641-641 
  V474Z     642-642 
  V475      643-643 
  V476      644-644 
  V477      645-646 
  V478      647-648 
  V479      649-650 
  V480      651-651 
  V481      652-652 
  V481A     653-653 
  V481B     654-654 
  V481C     655-655 
  V481D     656-656 
  V481E     657-657 
  V481F     658-658 
  V481G     659-659 
  V481H     660-660 
  V481X     661-661 
  V482A     662-662 
  V482B     663-663 
  V482C     664-664 
  V501      665-665 
  V502      666-666 
  V503      667-667 
  V504      668-668 
  V505      669-670 
  V506      671-672 
  V507      673-674 
  V508      675-678 
  V509      679-682 
  V510      683-683 
  V511      684-685 
  V512      686-687 
  V513      688-688 
  V525      689-690 
  V527      691-693 
  V528      694-695 
  V529      696-698 
  V530      699-699 
  V531      700-701 
  V532      702-702 
  V535      703-703 
  V536      704-704 
  V537      705-706 
  V538      707-707 
  V539      708-708 
  V540      709-709 
  V541      710-710 
  V602      711-711 
  V603      712-714 
  V604      715-715 
  V605      716-716 
  V613      717-718 
  V614      719-719 
  V616      720-722 
  V621      723-723 
  V623      724-724 
  V624      725-726 
  V625      727-727 
  V626      728-729 
  V625A     730-730 
  V626A     731-732 
  V627      733-734 
  V628      735-736 
  V629      737-738 
  V631      739-739 
  V632      740-740 
  V633A     741-741 
  V633B     742-742 
  V633C     743-743 
  V633D     744-744 
  V633E     745-745 
  V633F     746-746 
  V633G     747-747 
  V634      748-748 
  V701      749-749 
  V702      750-751 
  V704      752-754 
  V705      755-756 
  V714      757-757 
  V714A     758-758 
  V715      759-760 
  V716      761-763 
  V717      764-765 
  V719      766-766 
  V721      767-767 
  V729      768-768 
  V730      769-770 
  V731      771-771 
  V732      772-772 
  V739      773-773 
  V740      774-774 
  V741      775-775 
  V743A     776-776 
  V743B     777-777 
  V743C     778-778 
  V743D     779-779 
  V743E     780-780 
  V743F     781-781 
  V744A     782-782 
  V744B     783-783 
  V744C     784-784 
  V744D     785-785 
  V744E     786-786 
  V745A     787-787 
  V745B     788-788 
  V746      789-789 
  BIDX      790-791 
  BORD      792-793 
  B0        794-794 
  B1        795-796 
  B2        797-800 
  B3        801-804 
  B4        805-805 
  B5        806-806 
  B6        807-809 
  B7        810-812 
  B8        813-814 
  B9        815-815 
  B10       816-816 
  B11       817-819 
  B12       820-822 
  B13       823-823 
  B15       824-824 
  B16       825-826 
  M1        827-827 
  M1A       828-828 
  M1B       829-830 
  M1C       831-834 
  M1D       835-836 
  M1E       837-840 
  M2A       841-841 
  M2B       842-842 
  M2C       843-843 
  M2D       844-844 
  M2E       845-845 
  M2F       846-846 
  M2G       847-847 
  M2H       848-848 
  M2I       849-849 
  M2J       850-850 
  M2K       851-851 
  M2L       852-852 
  M2M       853-853 
  M2N       854-854 
  M3A       855-855 
  M3B       856-856 
  M3C       857-857 
  M3D       858-858 
  M3E       859-859 
  M3F       860-860 
  M3G       861-861 
  M3H       862-862 
  M3I       863-863 
  M3J       864-864 
  M3K       865-865 
  M3L       866-866 
  M3M       867-867 
  M3N       868-868 
  M4        869-870 
  M5        871-872 
  M6        873-874 
  M7        875-876 
  M8        877-878 
  M9        879-880 
  M10       881-881 
  M11       882-884 
  M13       885-886 
  M14       887-888 
  M15       889-890 
  M17       891-891 
  M18       892-892 
  M19       893-896 
  M19A      897-897 
  M27       898-898 
  M28       899-899 
  M29       900-900 
  M34       901-903 
  M35       904-905 
  M36       906-907 
  M38       908-908 
  M39A      909-909 
  M39       910-910 
  M42A      911-911 
  M42B      912-912 
  M42C      913-913 
  M42D      914-914 
  M42E      915-915 
  M43       916-916 
  M44       917-917 
  M45       918-918 
  M46       919-921 
  M47       922-922 
  M48       923-923 
  M49A      924-924 
  M49B      925-925 
  M49C      926-926 
  M49D      927-927 
  M49E      928-928 
  M49F      929-929 
  M49G      930-930 
  M49X      931-931 
  M49Z      932-932 
  M49Y      933-933 
  M50       934-934 
  M51       935-937 
  M52       938-939 
  M54       940-940 
  M55A      941-941 
  M55B      942-942 
  M55C      943-943 
  M55D      944-944 
  M55E      945-945 
  M55F      946-946 
  M55G      947-947 
  M55H      948-948 
  M55I      949-949 
  M55J      950-950 
  M55K      951-951 
  M55L      952-952 
  M55M      953-953 
  M55N      954-954 
  M55O      955-955 
  M55X      956-956 
  M55Z      957-957 
  M57A      958-958 
  M57B      959-959 
  M57C      960-960 
  M57D      961-961 
  M57E      962-962 
  M57F      963-963 
  M57G      964-964 
  M57H      965-965 
  M57I      966-966 
  M57J      967-967 
  M57K      968-968 
  M57L      969-969 
  M57M      970-970 
  M57N      971-971 
  M57O      972-972 
  M57P      973-973 
  M57Q      974-974 
  M57R      975-975 
  M57S      976-976 
  M57T      977-977 
  M57U      978-978 
  M57V      979-979 
  M57X      980-980 
  M60       981-981 
  M61       982-984 
  M62       985-985 
  M65A      986-986 
  M65B      987-987 
  M65C      988-988 
  M65D      989-989 
  M65E      990-990 
  M65F      991-991 
  M65G      992-992 
  M65H      993-993 
  M65I      994-994 
  M65J      995-995 
  M65K      996-996 
  M65L      997-997 
  M65X      998-998 
  M66       999-999 
  M70      1000-1000
  M71      1001-1003
  M72      1004-1005
  M73      1006-1007
  HIDX     1008-1008
  H1       1009-1009
  H2       1010-1010
  H2D      1011-1012
  H2M      1013-1014
  H2Y      1015-1018
  H3       1019-1019
  H3D      1020-1021
  H3M      1022-1023
  H3Y      1024-1027
  H4       1028-1028
  H4D      1029-1030
  H4M      1031-1032
  H4Y      1033-1036
  H5       1037-1037
  H5D      1038-1039
  H5M      1040-1041
  H5Y      1042-1045
  H6       1046-1046
  H6D      1047-1048
  H6M      1049-1050
  H6Y      1051-1054
  H7       1055-1055
  H7D      1056-1057
  H7M      1058-1059
  H7Y      1060-1063
  H8       1064-1064
  H8D      1065-1066
  H8M      1067-1068
  H8Y      1069-1072
  H9       1073-1073
  H9D      1074-1075
  H9M      1076-1077
  H9Y      1078-1081
  H0       1082-1082
  H0D      1083-1084
  H0M      1085-1086
  H0Y      1087-1090
  H10      1091-1091
  H11      1092-1092
  H11B     1093-1093
  H12A     1094-1094
  H12B     1095-1095
  H12C     1096-1096
  H12D     1097-1097
  H12E     1098-1098
  H12F     1099-1099
  H12G     1100-1100
  H12H     1101-1101
  H12I     1102-1102
  H12J     1103-1103
  H12K     1104-1104
  H12L     1105-1105
  H12M     1106-1106
  H12N     1107-1107
  H12O     1108-1108
  H12P     1109-1109
  H12Q     1110-1110
  H12R     1111-1111
  H12S     1112-1112
  H12T     1113-1113
  H12U     1114-1114
  H12V     1115-1115
  H12W     1116-1116
  H12X     1117-1117
  H12Y     1118-1118
  H12Z     1119-1119
  H13      1120-1120
  H13B     1121-1121
  H14      1122-1122
  H15      1123-1123
  H15A     1124-1124
  H15B     1125-1125
  H15C     1126-1126
  H15D     1127-1127
  H15E     1128-1128
  H15F     1129-1129
  H15G     1130-1130
  H15H     1131-1131
  H15I     1132-1132
  H15J     1133-1133
  H15K     1134-1134
  H15L     1135-1135
  H15M     1136-1136
  H20      1137-1137
  H21A     1138-1138
  H21      1139-1139
  H22      1140-1140
  H31      1141-1141
  H31B     1142-1142
  H31C     1143-1143
  H31D     1144-1144
  H31E     1145-1145
  H32A     1146-1146
  H32B     1147-1147
  H32C     1148-1148
  H32D     1149-1149
  H32E     1150-1150
  H32F     1151-1151
  H32G     1152-1152
  H32H     1153-1153
  H32I     1154-1154
  H32J     1155-1155
  H32K     1156-1156
  H32L     1157-1157
  H32M     1158-1158
  H32N     1159-1159
  H32O     1160-1160
  H32P     1161-1161
  H32Q     1162-1162
  H32R     1163-1163
  H32S     1164-1164
  H32T     1165-1165
  H32U     1166-1166
  H32V     1167-1167
  H32W     1168-1168
  H32X     1169-1169
  H32Y     1170-1170
  H32Z     1171-1171
  H33      1172-1172
  H33D     1173-1174
  H33M     1175-1176
  H33Y     1177-1180
  H34      1181-1181
  H35      1182-1182
  H36A     1183-1183
  H36B     1184-1184
  H36C     1185-1185
  H36D     1186-1186
  H36E     1187-1187
  H36F     1188-1188
  H37A     1189-1189
  H37B     1190-1190
  H37C     1191-1191
  H37D     1192-1192
  H37E     1193-1193
  H37F     1194-1194
  H37G     1195-1195
  H37H     1196-1196
  H37I     1197-1197
  H37J     1198-1198
  H37K     1199-1199
  H37L     1200-1200
  H37M     1201-1201
  H37N     1202-1202
  H37O     1203-1203
  H37P     1204-1204
  H37X     1205-1205
  H37Y     1206-1206
  H37Z     1207-1207
  H38      1208-1208
  H39      1209-1209
  H40      1210-1210
  H40D     1211-1212
  H40M     1213-1214
  H40Y     1215-1218
  H41A     1219-1219
  H41B     1220-1220
  H42      1221-1221
  H43      1222-1222
  H44A     1223-1224
  H44B     1225-1226
  H44C     1227-1227
  H45      1228-1229
  H46A     1230-1231
  H46B     1232-1233
  H47      1234-1234
  HWIDX    1235-1235
  HW1      1236-1237
  HW2      1238-1241
  HW3      1242-1245
  HW4      1246-1249
  HW5      1250-1253
  HW6      1254-1258
  HW7      1259-1262
  HW8      1263-1266
  HW9      1267-1271
  HW10     1272-1275
  HW11     1276-1279
  HW12     1280-1284
  HW13     1285-1285
  HW15     1286-1286
  HW16     1287-1288
  HW17     1289-1290
  HW18     1291-1292
  HW19     1293-1296
  HW51     1297-1298
  HW52     1299-1299
  HW53     1300-1302
  HW55     1303-1303
  HW56     1304-1307
  HW57     1308-1308
  HW58     1309-1309
  HW70     1310-1313
  HW71     1314-1317
  HW72     1318-1321
  HW73     1322-1325
  IDXML    1326-1326
  ML0      1327-1327
  ML1      1328-1329
  ML2      1330-1330
  ML11     1331-1331
  ML12     1332-1332
  ML13A    1333-1333
  ML13B    1334-1334
  ML13C    1335-1335
  ML13D    1336-1336
  ML13E    1337-1337
  ML13F    1338-1338
  ML13G    1339-1339
  ML13H    1340-1340
  ML13I    1341-1341
  ML13J    1342-1342
  ML13K    1343-1343
  ML13L    1344-1344
  ML13M    1345-1345
  ML13N    1346-1346
  ML13O    1347-1347
  ML13P    1348-1348
  ML13X    1349-1349
  ML13Y    1350-1350
  ML13Z    1351-1351
  ML14A    1352-1352
  ML14B    1353-1353
  ML14Y    1354-1354
  ML14Z    1355-1355
  ML15A    1356-1356
  ML15B    1357-1357
  ML15C    1358-1358
  ML16A    1359-1359
  ML16B    1360-1360
  ML16C    1361-1361
  ML17A    1362-1362
  ML17B    1363-1363
  ML17C    1364-1364
  ML18A    1365-1365
  ML18B    1366-1366
  ML18C    1367-1367
  ML19A    1368-1368
  ML19B    1369-1369
  ML19C    1370-1370
  ML19D    1371-1371
  ML19E    1372-1372
  ML19F    1373-1373
  ML19X    1374-1374
  ML19Y    1375-1375
  ML19Z    1376-1376
  ML20A    1377-1377
  ML20B    1378-1378
  ML20C    1379-1379
  ML21A    1380-1380
  ML21B    1381-1381
  ML21C    1382-1382
  ML22A    1383-1383
  ML22B    1384-1384
  ML22C    1385-1385
  ML23A    1386-1386
  ML23B    1387-1387
  ML23C    1388-1388
  ML24C    1389-1389
  SLANG    1390-1390
  STRANS   1391-1391
  SDISTRICT 1392-1393
  S105     1394-1394
  S106     1395-1396
  S106A    1397-1397
  S115     1398-1400
  S205CA   1401-1401
  S205CB   1402-1402
  S205CC   1403-1403
  S205CD   1404-1404
  S205CE   1405-1405
  S205CX   1406-1406
  S205CZ   1407-1407
  S564     1408-1409
  S564A    1410-1411
  S566     1412-1413
  S567A    1414-1414
  S567B    1415-1415
  S567C    1416-1416
  S568A    1417-1417
  S568B    1418-1418
  S570     1419-1420
  S570A    1421-1422
  S572     1423-1423
  S573     1424-1425
  S574AA   1426-1426
  S574AB   1427-1427
  S574AX   1428-1428
  S574AY   1429-1429
  S574BA   1430-1430
  S574BB   1431-1431
  S574BX   1432-1432
  S574BY   1433-1433
  S574CA   1434-1434
  S574CB   1435-1435
  S574CX   1436-1436
  S574CY   1437-1437
  S574DA   1438-1438
  S574DB   1439-1439
  S574DX   1440-1440
  S574DY   1441-1441
  S574EA   1442-1442
  S574EB   1443-1443
  S574EX   1444-1444
  S574EY   1445-1445
  S574FA   1446-1446
  S574FB   1447-1447
  S574FX   1448-1448
  S574FY   1449-1449
  S575     1450-1450
  S576     1451-1451
  S577     1452-1452
  S578     1453-1453
  S579     1454-1454
  S580     1455-1455
  S581     1456-1456
  S582     1457-1457
  S583     1458-1458
  S584     1459-1459
  S623A    1460-1461
  S623B    1462-1463
  S623C    1464-1465
  S626A    1466-1467
  S714D    1468-1468
  S826E    1469-1469
  S827A    1470-1470
  S827B    1471-1471
  S827C    1472-1472
  S907A    1473-1473
  S910B    1474-1474
  S910D    1475-1475
  S910E    1476-1476
  S1011A   1477-1477
  S1011B   1478-1478
  S1011C   1479-1479
  S1011D   1480-1480
  S1011E   1481-1481
  S1011F   1482-1482
  S1013    1483-1483
  S1014A   1484-1484
  S1014B   1485-1485
  S1014C   1486-1486
  S1014D   1487-1487
  S1014E   1488-1488
  S1014F   1489-1489
  S1014I   1490-1490
  S1014J   1491-1491
  S1014K   1492-1492
  S1014M   1493-1493
  S1014N   1494-1494
  S1014O   1495-1495
  S1014P   1496-1496
  S1014S   1497-1497
  S1014T   1498-1498
  S1014V   1499-1499
  S1014X   1500-1500
  SDV18    1501-1501
  SDV18C   1502-1503
  SDV24    1504-1504
  SDV24A   1505-1506
  IDX94    1507-1507
  S412B    1508-1509
  S412D    1510-1511
  S412F    1512-1513
  S425AA   1514-1514
  S425AB   1515-1515
  S425AC   1516-1516
  S425AD   1517-1517
  S425AE   1518-1518
  S425AF   1519-1519
  S425AI   1520-1520
  S425AJ   1521-1521
  S425AK   1522-1522
  S425AM   1523-1523
  S425AN   1524-1524
  S425AP   1525-1525
  S425AS   1526-1526
  S425AT   1527-1527
  S425AU   1528-1528
  S425AV   1529-1529
  S425AX   1530-1530
  S435A    1531-1531
  S452U    1532-1532
  S452N    1533-1534
  S460B    1535-1536
  IDX95    1537-1537
  S506N1   1538-1538
  S506N1D  1539-1540
  S506N1M  1541-1542
  S506N1Y  1543-1546
  S506N2   1547-1547
  S506N2D  1548-1549
  S506N2M  1550-1551
  S506N2Y  1552-1555
  S506N3   1556-1556
  S506N3D  1557-1558
  S506N3M  1559-1560
  S506N3Y  1561-1564
  S506R1   1565-1565
  S506R1D  1566-1567
  S506R1M  1568-1569
  S506R1Y  1570-1573
  S506R2   1574-1574
  S506R2D  1575-1576
  S506R2M  1577-1578
  S506R2Y  1579-1582
  S506R3   1583-1583
  S506R3D  1584-1585
  S506R3M  1586-1587
  S506R3Y  1588-1591
  S506MR   1592-1592
  S506MRD  1593-1594
  S506MRM  1595-1596
  S506MRY  1597-1600
  S517B    1601-1601
  S561A    1602-1602
  S561BA   1603-1603
  S561BB   1604-1604
  S561BC   1605-1605
  S561BD   1606-1606
  S561BX   1607-1607
 .
VARIABLE LABELS
   CASEID   "Case Identification"
  /MIDX     "Index to Birth History"
  /V000     "Country code and phase"
  /V001     "Cluster number"
  /V002     "Household number"
  /V003     "Respondent's line number"
  /V004     "Ultimate area unit"
  /V005     "Women's individual sample weight (6 decimals)"
  /V006     "Month of interview"
  /V007     "Year of interview"
  /V008     "Date of interview (CMC)"
  /V009     "Respondent's month of birth"
  /V010     "Respondent's year of birth"
  /V011     "Date of birth (CMC)"
  /V012     "Respondent's current age"
  /V013     "Age in 5-year groups"
  /V014     "Completeness of age information"
  /V015     "Result of individual interview"
  /V016     "Day of interview"
  /V017     "CMC start of calendar"
  /V018     "Row of month of interview"
  /V019     "Length of calendar"
  /V019A    "Number of calendar columns"
  /V020     "Ever-married sample"
  /V021     "Primary sampling unit"
  /V022     "Sample strata for sampling errors"
  /V023     "Stratification used in sample design"
  /V024     "Province"
  /V025     "Type of place of residence"
  /V026     "NA - De facto place of residence"
  /V027     "Number of visits"
  /V028     "Interviewer identification"
  /V029     "Keyer identification"
  /V030     "Field supervisor"
  /V031     "Field editor"
  /V032     "Office editor"
  /V034     "Line number of husband"
  /V040     "Cluster altitude in meters"
  /V042     "Selected for Anthropometry, Anemia, Malaria"
  /V044     "Selected for female Domestic Violence"
  /V101     "Province"
  /V102     "Type of place of residence"
  /V103     "NA - Childhood place of residence"
  /V104     "NA - Years lived in place of residence"
  /V105     "NA - Type of place of previous residence"
  /V106     "Highest educational level"
  /V107     "Highest year of education"
  /V113     "Source of drinking water"
  /V115     "Time to get to water source"
  /V116     "Type of toilet facility"
  /V119     "Household has: electricity"
  /V120     "Household has: radio"
  /V121     "Household has: television"
  /V122     "Household has: refrigerator"
  /V123     "Household has: bicycle"
  /V124     "Household has: motorcycle/scooter"
  /V125     "Household has: car/truck"
  /V127     "Main floor material"
  /V128     "Main wall material"
  /V129     "Main roof material"
  /V130     "Religion"
  /V131     "NA - Ethnicity"
  /V133     "Education in single years"
  /V134     "NA - De facto place of residence"
  /V135     "Usual resident or visitor"
  /V136     "Number of household members (listed)"
  /V137     "Number of children 5 and under in household (de jure)"
  /V138     "Number of eligible women in household (de facto)"
  /V139     "De jure region of residence"
  /V140     "De jure type of place of residence"
  /V141     "NA - De jure place of residence"
  /V149     "Educational attainment"
  /V150     "Relationship to household head"
  /V151     "Sex of household head"
  /V152     "Age of household head"
  /V153     "Household has: telephone (land-line)"
  /AWFACTT  "All woman factor - total"
  /AWFACTU  "All woman factor - urban/rural"
  /AWFACTR  "All woman factor - regional"
  /AWFACTE  "All woman factor - educational"
  /AWFACTW  "All woman factor - wealth index"
  /V155     "Literacy"
  /V156     "NA - Ever participated in a literacy program outside of primary"
  /V157     "Frequency of reading newspaper or magazine"
  /V158     "Frequency of listening to radio"
  /V159     "Frequency of watching television"
  /V160     "Toilet facilities shared with other households"
  /V161     "Type of cooking fuel"
  /V166     "NA - Result of salt test for iodine"
  /V167     "Number of trips in last 12 months"
  /V168     "Away for more than one month in last 12 months"
  /V190     "Wealth index"
  /V191     "Wealth index factor score (5 decimals)"
  /ML101    "Type of mosquito bed net(s) slept under last night"
  /V201     "Total children ever born"
  /V202     "Sons at home"
  /V203     "Daughters at home"
  /V204     "Sons elsewhere"
  /V205     "Daughters elsewhere"
  /V206     "Sons who have died"
  /V207     "Daughters who have died"
  /V208     "Births in last five years"
  /V209     "Births in past year"
  /V210     "Births in month of interview"
  /V211     "Date of first birth (CMC)"
  /V212     "Age of respondent at 1st birth"
  /V213     "Currently pregnant"
  /V214     "Duration of current pregnancy"
  /V215     "Time since last menstrual period"
  /V216     "Menstruated in last six weeks"
  /V217     "Knowledge of ovulatory cycle"
  /V218     "Number of living children"
  /V219     "Living children + current pregnancy"
  /V220     "Living children + current pregnancy (grouped)"
  /V221     "Marriage to first birth interval (months)"
  /V222     "Last birth to interview (months)"
  /V223     "Completeness of current pregnancy information"
  /V224     "Entries in birth history"
  /V225     "Current pregnancy wanted"
  /V226     "Time since last period (comp) (months)"
  /V227     "Flag for last period"
  /V228     "Ever had a terminated pregnancy"
  /V229     "Month pregnancy ended"
  /V230     "Year pregnancy ended"
  /V231     "CMC pregnancy ended"
  /V232     "Completeness of last termination information"
  /V233     "Months when pregnancy ended"
  /V234     "Other such pregnancies"
  /V235     "Index last child prior to maternity-health (calendar)"
  /V237     "Birth between last and interview"
  /V238     "Births in last three years"
  /V239     "Pregnancies terminated before calendar beginning"
  /V240     "Month of last termination prior to calendar"
  /V241     "Year of last termination prior to calendar"
  /V242     "CMC termination ended prior to calendar"
  /V243     "Completeness of last termination date prior to calendar"
  /V310     "NA - Living children at first use"
  /V311     "NA - Children at first use (grouped)"
  /V312     "Current contraceptive method"
  /V313     "Current use by method type"
  /V315     "Month of start of use of method"
  /V316     "Year of start of use of method"
  /V317     "Date of start of use of method (CMC)"
  /V318     "Completeness of information"
  /V319     "Years since sterilization"
  /V320     "Age at sterilization"
  /V321     "Marital duration at sterilization"
  /V322     "Parity at sterilization"
  /V323     "Brand of pill used"
  /V323A    "Brand of condom used"
  /V325A    "NA - Cost of current method (in CURRENCY)"
  /V326     "Last source for current users"
  /V327     "Last source for users by type"
  /V337     "Months of use of current method"
  /V359     "Last method discontinued in last 5 years"
  /V360     "Reason of last discontinuation"
  /V361     "Pattern of use"
  /V362     "Intention to use"
  /V363     "NA - Preferred future method"
  /V364     "Contraceptive use and intention"
  /V367     "Wanted last child"
  /V372     "NA - Shown pill package"
  /V372A    "NA - Shown condom package"
  /V375A    "NA - Main reason not using a method"
  /V376     "NA - Main reason not to use a method"
  /V376A    "NA - Would ever use method if married"
  /V379     "NA - Source known for any method"
  /V380     "NA - Source known for any method"
  /V384A    "Heard family planning on radio last few months"
  /V384B    "Heard family planning on TV last few months"
  /V384C    "Heard family planning in newspaper/magazine last few months"
  /V393     "Visited by family planning worker last 12 months"
  /V394     "Visited health facility last 12 months"
  /V395     "At health facility, told of family planning"
  /V3A00A   "Source of family planning for non-users: government hospital"
  /V3A00B   "Source of family planning for non-users: provincial/district hospital"
  /V3A00C   "Source of family planning for non-users: health center"
  /V3A00D   "Source of family planning for non-users: health post"
  /V3A00E   "Source of family planning for non-users: outreach"
  /V3A00F   "Source of family planning for non-users: community health worker"
  /V3A00G   "Source of family planning for non-users: youth center"
  /V3A00H   "NA - Source of family planning for non-users: CS public sector"
  /V3A00I   "Source of family planning for non-users: other public health facility"
  /V3A00J   "Source of family planning for non-users: private hospital/clinic"
  /V3A00K   "Source of family planning for non-users: pharmacy"
  /V3A00L   "NA - Source of family planning for non-users: private doctor"
  /V3A00M   "Source of family planning for non-users: polyclinic"
  /V3A00N   "Source of family planning for non-users: dispensary"
  /V3A00O   "Source of family planning for non-users: family planning clinic"
  /V3A00P   "Source of family planning for non-users: other private health facility"
  /V3A00Q   "NA - Source of family planning for non-users: CS private sector"
  /V3A00R   "NA - Source of family planning for non-users: CS private sector"
  /V3A00S   "Source of family planning for non-users: kiosk"
  /V3A00T   "NA - Source of family planning for non-users: traditional healer"
  /V3A00U   "Source of family planning for non-users: church"
  /V3A00V   "Source of family planning for non-users: friend/relative"
  /V3A00W   "NA - Source of family planning for non-users: CS other"
  /V3A00X   "Source of family planning for non-users: other"
  /V3A00Y   "Source of family planning for non-users: no source"
  /V3A00Z   "Source of family planning for non-users: any source"
  /V3A01    "NA - Told sterilization would mean no more children"
  /V3A02    "Told about side effects"
  /V3A03    "Told about side effects by health or family planning worker"
  /V3A04    "Told how to deal with side effects"
  /V3A05    "Told about other family planning methods"
  /V3A06    "Told about other family planning methods by health or family planning worker"
  /V3A07    "First source for current method"
  /V3A08A   "Reason not using: not married"
  /V3A08B   "Reason not using: not having sex"
  /V3A08C   "Reason not using: infrequent sex"
  /V3A08D   "Reason not using: menopausal/hysterectomy"
  /V3A08E   "Reason not using: subfecund/infecund"
  /V3A08F   "Reason not using: postpartum amenorrheic"
  /V3A08G   "Reason not using: breastfeeding"
  /V3A08H   "Reason not using: fatalistic"
  /V3A08I   "Reason not using: respondent opposed"
  /V3A08J   "Reason not using: husband/partner opposed"
  /V3A08K   "Reason not using: others opposed"
  /V3A08L   "Reason not using: religious prohibition"
  /V3A08M   "Reason not using: knows no method"
  /V3A08N   "Reason not using: knows no source"
  /V3A08O   "NA - Reason not using: health concerns"
  /V3A08P   "Reason not using: fear of side effects/health concerns"
  /V3A08Q   "Reason not using: lack of access/too far"
  /V3A08R   "Reason not using: costs too much"
  /V3A08S   "Reason not using: inconvenient to use"
  /V3A08T   "Reason not using: interferes with body's processes"
  /V3A08U   "Reason not using: preferred method not available"
  /V3A08V   "Reason not using: no method available"
  /V3A08W   "NA - Reason not using: CS"
  /V3A08AA  "NA - Reason not using: CS"
  /V3A08AB  "NA - Reason not using: CS"
  /V3A08AC  "NA - Reason not using: CS"
  /V3A08AD  "NA - Reason not using: CS"
  /V3A08X   "Reason not using: other"
  /V3A08Z   "Reason not using: don't know"
  /V3A09A   "NA - How many pill cycles did get last time"
  /V3A09B   "NA - How many condoms did get last time"
  /V401     "Last birth a Caesarean section"
  /V404     "Currently breastfeeding"
  /V405     "Currently amenorrheic"
  /V406     "Currently abstaining"
  /V407     "NA - Number of times breastfed during night"
  /V408     "NA - Number of times breastfed during day"
  /V409     "Gave child plain water"
  /V409A    "NA - Gave child sugar water"
  /V410     "Gave child juice"
  /V410A    "NA - Gave child tea or coffee"
  /V411     "Gave child tinned, powdered or fresh milk"
  /V411A    "Gave child baby formula"
  /V412     "NA - Gave child fresh milk"
  /V412A    "Gave child fortified baby food (Cerelac, etc)"
  /V412B    "NA - Gave child other porridge/gruel"
  /V412C    "Gave child soup/clear broth"
  /V413     "Gave child other liquid"
  /V413A    "NA - Gave child CS liquid"
  /V413B    "NA - Gave child CS liquid"
  /V413C    "NA - Gave child CS liquid"
  /V413D    "NA - Gave child CS liquid"
  /V414A    "NA - Gave child CS foods"
  /V414B    "NA - Gave child CS foods"
  /V414C    "NA - Gave child CS foods"
  /V414D    "NA - Gave child CS foods"
  /V414E    "Gave child bread, noodles, other made from grains"
  /V414F    "Gave child potatoes, cassava, or other tubers"
  /V414G    "Gave child eggs"
  /V414H    "Gave child meat (beef, pork, lamb, chicken, etc)"
  /V414I    "Gave child pumpkin, carrots, squash (yellow or orange inside)"
  /V414J    "Gave child any dark green leafy vegetables"
  /V414K    "Gave child mangoes, papayas, other vitamin A fruits"
  /V414L    "Gave child any other fruits"
  /V414M    "Gave child liver, heart, other organs"
  /V414N    "Gave child fish or shellfish"
  /V414O    "Gave child food made from beans, peas, lentils, nuts"
  /V414P    "Gave child cheese, yogurt, other milk products"
  /V414Q    "NA - Gave child oil, fats, butter, products made of them"
  /V414R    "NA - Gave child chocolates, sweets, candies, pastries, etc"
  /V414S    "Gave child other solid-semisolid food"
  /V414T    "NA - Gave child CS foods"
  /V414U    "NA - Gave child CS foods"
  /V414V    "Gave child yogurt"
  /V414W    "NA - Gave child CS foods"
  /V415     "Drank from bottle with nipple yesterday/last night"
  /V416     "Heard of oral rehydration"
  /V417     "Entries in maternity table"
  /V418     "Entries in health table"
  /V419     "Entries in height/weight table"
  /V420     "NA - Measurer's code"
  /V421     "NA - Assistant measurer's code"
  /V426     "When child put to breast"
  /V437     "Respondent's weight in kilograms (1 decimal)"
  /V438     "Respondent's height in centimeters (1 decimal)"
  /V439     "Height/Age percentile"
  /V440     "Height/Age standard deviation"
  /V441     "Height/Age percent ref. median"
  /V442     "Weight/Height percent ref. median (DHS)"
  /V443     "Weight/Height percent ref. median (Fog)"
  /V444     "Weight/Height percent ref. median (WHO)"
  /V444A    "Weight/Height standard deviation (DHS)"
  /V445     "Body Mass Index"
  /V446     "Rohrer's index"
  /V447     "Result of measurement - height/weight"
  /V447A    "Women's age in years (from household questionnaire)"
  /V452A    "Under age 18 (from household questionnaire)"
  /V452B    "Line number of parent/caretaker"
  /V452C    "Read consent statement - hemoglobin"
  /V453     "Hemoglobin level (g/dl - 1 decimal)"
  /V454     "Currently pregnant (from household questionnaire)"
  /V455     "Result of measurement - hemoglobin"
  /V456     "Hemoglobin level adjusted for altitude and smoking (g/dl - 1 decimal)"
  /V457     "Anemia level"
  /V458     "NA - Agrees to referral - anemia"
  /V459     "Have mosquito bed net for sleeping (from household questionnaire)"
  /V460     "Children under 5 slept under mosquito bed net last night (household questionnaire)"
  /V461     "Respondent slept under mosquito bed net"
  /V462     "NA - Washed hands before preparing last meal"
  /V463A    "Smokes cigarettes"
  /V463B    "Smokes pipe"
  /V463C    "Uses chewing tobacco"
  /V463D    "Uses snuff"
  /V463E    "NA - Smokes cigars"
  /V463F    "NA - Smokes country specific"
  /V463G    "NA - Smokes country specific"
  /V463X    "Smokes other"
  /V463Z    "Does not use tobacco"
  /V464     "Number of cigarettes in last 24 hours"
  /V465     "Disposal of youngest child's stools when not using toilet"
  /V466     "NA - When child is seriously ill, can decide whether medical treatment sought"
  /V467A    "NA - Getting medical help for self: know where to go"
  /V467B    "Getting medical help for self: getting permission to go"
  /V467C    "Getting medical help for self: getting money needed for treatment"
  /V467D    "Getting medical help for self: distance to health facility"
  /V467E    "NA - Getting medical help for self: having to take transport"
  /V467F    "Getting medical help for self: not wanting to go alone"
  /V467G    "NA - Getting medical help for self: concern no female health provider"
  /V467H    "NA - Getting medical help for self: concern no provider"
  /V467I    "NA - Getting medical help for self: concern no drugs available"
  /V467J    "NA - Getting medical help for self: CS"
  /V467K    "NA - Getting medical help for self: CS"
  /V467L    "NA - Getting medical help for self: CS"
  /V467M    "NA - Getting medical help for self: CS"
  /V468     "Record for Last Birth"
  /V469E    "Times gave child powdered/tinned/fresh milk"
  /V469F    "Times gave child infant formula"
  /V469X    "Times gave child yogurt"
  /V471A    "NA - Mother had tinned, powdered or fresh milk"
  /V471B    "NA - Mother had tea or coffee"
  /V471C    "NA - Mother had any other liquid"
  /V471D    "NA - Mother had CS liquid"
  /V471E    "NA - Mother had CS liquid"
  /V471F    "NA - Mother had CS liquid"
  /V471G    "NA - Mother had CS liquid"
  /V472A    "NA - Mother had CS foods"
  /V472B    "NA - Mother had CS foods"
  /V472C    "NA - Mother had CS foods"
  /V472D    "NA - Mother had CS foods"
  /V472E    "NA - Mother had bread, noodles, other made from grains"
  /V472F    "NA - Mother had potatoes, cassava, or other tubers"
  /V472G    "NA - Mother had eggs"
  /V472H    "NA - Mother had meat (beef, pork, lamb, chicken, etc)"
  /V472I    "NA - Mother had pumpkin, carrots, squash (yellow or orange inside)"
  /V472J    "NA - Mother had any dark green leafy vegetables"
  /V472K    "NA - Mother had mangoes, papayas, other vitamin A fruits"
  /V472L    "NA - Mother had any other fruits"
  /V472M    "NA - Mother had liver, heart, other organs"
  /V472N    "NA - Mother had fish or shellfish"
  /V472O    "NA - Mother had food made from beans, peas, lentils, nuts"
  /V472P    "NA - Mother had cheese, yogurt, other milk products"
  /V472Q    "NA - Mother had oil, fats, butter, products made of them"
  /V472R    "NA - Mother had chocolates, sweets, candies, pastries, etc"
  /V472S    "NA - Mother had other solid-semisolid food"
  /V472T    "NA - Mother had CS foods"
  /V472U    "NA - Mother had CS foods"
  /V473A    "Read consent statement - HIV"
  /V473B    "Result of measurement - HIV"
  /V474     "Heard of tuberculosis or TB"
  /V474A    "Tuberculosis spread by: air when coughing or sneezing"
  /V474B    "Tuberculosis spread by: sharing utensils"
  /V474C    "Tuberculosis spread by: touching a person with TB"
  /V474D    "Tuberculosis spread by: food"
  /V474E    "Tuberculosis spread by: sexual contact"
  /V474F    "Tuberculosis spread by: mosquito bites"
  /V474G    "Tuberculosis spread by: smoking"
  /V474H    "Tuberculosis spread by: HIV / other illnesses"
  /V474I    "Tuberculosis spread by: Witchcraft"
  /V474J    "Tuberculosis spread by: cow milk, eggs, meat"
  /V474K    "Tuberculosis spread by: unsafe water or food"
  /V474X    "Tuberculosis spread by: other"
  /V474Z    "Tuberculosis spread by: don't know"
  /V475     "NA - Tuberculosis can be cured"
  /V476     "NA - Keep secret when family member gets TB"
  /V477     "Number of injections in last 12 months"
  /V478     "Number of injections administered by a health worker"
  /V479     "NA - Place of injection by health worker"
  /V480     "Syringe and needle from new, unopened package"
  /V481     "NA - Covered by health insurance"
  /V481A    "NA - Health insurance type: mutual/community organization"
  /V481B    "NA - Health insurance type: provided by employer"
  /V481C    "NA - Health insurance type: social security"
  /V481D    "NA - Health insurance type: private/commercially purchased"
  /V481E    "NA - Health insurance type: CS"
  /V481F    "NA - Health insurance type: CS"
  /V481G    "NA - Health insurance type: CS"
  /V481H    "NA - Health insurance type: CS"
  /V481X    "NA - Health insurance type: other"
  /V482A    "NA - Arrange care of biological children under age 18"
  /V482B    "NA - Primary caregiver of children under age 18"
  /V482C    "NA - Arrange care of non-biological children < 18"
  /V501     "Current marital status"
  /V502     "Currently/formerly/never in union"
  /V503     "Number of unions"
  /V504     "Currently residing with husband/partner"
  /V505     "Number of other wives"
  /V506     "Respondent's rank among wives"
  /V507     "Month of first cohabitation"
  /V508     "Year of first cohabitation"
  /V509     "Date of first cohabitation (CMC)"
  /V510     "Completeness of date information in V509"
  /V511     "Age at first cohabitation"
  /V512     "Years since first cohabitation"
  /V513     "Cohabitation duration (grouped)"
  /V525     "Age at first sex"
  /V527     "Time since last sex"
  /V528     "Time since last sex (in days)"
  /V529     "Time since last sex (in months)"
  /V530     "Flag for V529"
  /V531     "Age at first sex (imputed)"
  /V532     "Flag for V531"
  /V535     "Ever been married or in union"
  /V536     "Recent sexual activity"
  /V537     "Months of abstinence"
  /V538     "NA - How previous marriage or union ended"
  /V539     "NA - Person who received most of late husband's property"
  /V540     "NA - Respondent received any of late husband's assets or valuables"
  /V541     "NA - Intends to wait until marriage to have sex"
  /V602     "Fertility preference"
  /V603     "Preferred waiting time for birth of a/another child"
  /V604     "Preferred waiting time for birth of a/another child (grouped)"
  /V605     "Desire for more children"
  /V613     "Ideal number of children"
  /V614     "Ideal number of children (grouped)"
  /V616     "Time for future birth"
  /V621     "Husband's desire for children"
  /V623     "Exposure"
  /V624     "Unmet need"
  /V625     "Exposure (definition 2)"
  /V626     "Unmet need (definition 2)"
  /V625A    "Exposure to need for contraception (definition 3)"
  /V626A    "Unmet need for contraception (definition 3)"
  /V627     "Ideal number of boys"
  /V628     "Ideal number of girls"
  /V629     "Ideal number of either sex"
  /V631     "NA - Problem if became pregnant"
  /V632     "Decision maker for using contraception"
  /V633A    "NA - Reason for not having sex: husband has STI"
  /V633B    "Reason for not having sex: husband has other women"
  /V633C    "NA - Reason for not having sex: recent birth"
  /V633D    "NA - Reason for not having sex: tired, not in mood"
  /V633E    "NA - Reason for not having sex: CS"
  /V633F    "NA - Reason for not having sex: CS"
  /V633G    "NA - Reason for not having sex: CS"
  /V634     "NA - Husband knows that respondent is using contraception"
  /V701     "Husband/partner's education level"
  /V702     "Husband/partner's highest year of education (at level in V701)"
  /V704     "Husband/partner's occupation"
  /V705     "Husband/partner's occupation (grouped)"
  /V714     "Respondent currently working"
  /V714A    "Respondent has a job, but currently absent"
  /V715     "Husband/partner's total number of years of education"
  /V716     "Respondent's occupation"
  /V717     "Respondent's occupation (grouped)"
  /V719     "Respondent works for family, others, self"
  /V721     "NA - Respondent works at home or away"
  /V729     "Husband/partner's educational attainment"
  /V730     "Husband/partner's age"
  /V731     "Respondent worked in last 12 months"
  /V732     "Respondent employed all year/seasonal"
  /V739     "Person who usually decides how to spend respondent's earnings"
  /V740     "NA - Type of land where respondent works"
  /V741     "Type of earnings from respondent's work"
  /V743A    "Person who usually decides on respondent's health care"
  /V743B    "Person who usually decides on large household purchases"
  /V743C    "NA - Person who usually decides on household purchases for daily needs"
  /V743D    "Person who usually decides on visits to family or relatives"
  /V743E    "NA - Person who usually decides on food to be cooked each day"
  /V743F    "Person who usually decides what to do with money husband earns"
  /V744A    "Beating justified if wife goes out without telling husband"
  /V744B    "Beating justified if wife neglects the children"
  /V744C    "Beating justified if wife argues with husband"
  /V744D    "Beating justified if wife refuses to have sex with husband"
  /V744E    "Beating justified if wife burns the food"
  /V745A    "Owns a house alone or jointly"
  /V745B    "Owns land alone or jointly"
  /V746     "Respondent earns more than husband/partner"
  /BIDX     "Birth column number"
  /BORD     "Birth order number"
  /B0       "Child is twin"
  /B1       "Month of birth"
  /B2       "Year of birth"
  /B3       "Date of birth (CMC)"
  /B4       "Sex of child"
  /B5       "Child is alive"
  /B6       "Age at death"
  /B7       "Age at death (months, imputed)"
  /B8       "Current age of child"
  /B9       "Child lives with whom"
  /B10      "Completeness of information"
  /B11      "Preceding birth interval (months)"
  /B12      "Succeeding birth interval (months)"
  /B13      "Flag for age at death"
  /B15      "Live birth between births"
  /B16      "Child's line number in household"
  /M1       "Number of tetanus injections before birth"
  /M1A      "Number of tetanus injections before pregnancy"
  /M1B      "NA - Month of last tetanus injection before pregnancy"
  /M1C      "NA - Year of last tetanus injection before pregnancy"
  /M1D      "Years ago received last tetanus injection before pregnancy"
  /M1E      "NA - Last tetanus injection before pregnancy (CMC)"
  /M2A      "Prenatal: doctor"
  /M2B      "Prenatal: nurse/medical assistant"
  /M2C      "Prenatal: midwife"
  /M2D      "NA - Prenatal: CS health professional"
  /M2E      "NA - Prenatal: CS health professional"
  /M2F      "NA - Prenatal: CS health professional"
  /M2G      "Prenatal: traditional healer"
  /M2H      "Prenatal: community health worker"
  /M2I      "Prenatal: community health mother and child"
  /M2J      "NA - Prenatal: CS other person"
  /M2K      "NA - Prenatal: CS other"
  /M2L      "NA - Prenatal: CS other"
  /M2M      "Prenatal: other"
  /M2N      "Prenatal: no one"
  /M3A      "Assistance: doctor"
  /M3B      "Assistance: nurse/medical assistant"
  /M3C      "Assistance: midwife"
  /M3D      "NA - Assistance: CS health professional"
  /M3E      "NA - Assistance: CS health professional"
  /M3F      "NA - Assistance: CS health professional"
  /M3G      "Assistance: traditional healer"
  /M3H      "Assistance: community health worker"
  /M3I      "Assistance: community health mother and child"
  /M3J      "Assistance: relatives"
  /M3K      "Assistance: friends and neighbors"
  /M3L      "NA - Assistance: CS other"
  /M3M      "Assistance: other"
  /M3N      "Assistance: no one"
  /M4       "Duration of breastfeeding"
  /M5       "Months of breastfeeding"
  /M6       "Duration of amenorrhea"
  /M7       "Months of amenorrhea"
  /M8       "Duration of abstinence"
  /M9       "Months of abstinence"
  /M10      "Wanted pregnancy when became pregnant"
  /M11      "Desired time would have waited"
  /M13      "Timing of 1st antenatal check (months)"
  /M14      "Number of antenatal visits during pregnancy"
  /M15      "Place of delivery"
  /M17      "Delivery by Caesarean section"
  /M18      "Size of child at birth"
  /M19      "Birth weight in kilograms (3 decimals)"
  /M19A     "Weight at birth/recall"
  /M27      "NA - Flag for breastfeeding"
  /M28      "Flag for amenorrhea"
  /M29      "Flag for abstinence"
  /M34      "When child put to breast"
  /M35      "NA - Number of times breastfed during previous night"
  /M36      "NA - Number of times breastfed during previous day"
  /M38      "Drank from bottle with nipple yesterday/last night"
  /M39A     "Did eat any solid, semi-solid or soft foods yesterday"
  /M39      "Number of times ate solid, semi-solid or soft food yesterday"
  /M42A     "NA - During pregnancy: weighed"
  /M42B     "NA - During pregnancy: height measured"
  /M42C     "During pregnancy: blood pressure taken"
  /M42D     "During pregnancy: urine sample taken"
  /M42E     "During pregnancy: blood sample taken"
  /M43      "Told about pregnancy complications"
  /M44      "NA - Told where to go for pregnancy complications"
  /M45      "During pregnancy, given or bought iron tablets/syrup"
  /M46      "Days tablets or syrup taken"
  /M47      "NA - During pregnancy, had difficulty with daylight vision"
  /M48      "NA - During pregnancy, had difficulty with night blindness"
  /M49A     "NA - During pregnancy took: SP/fansidar for malaria"
  /M49B     "NA - During pregnancy took: chloroquine for malaria"
  /M49C     "During pregnancy took: Coartem for malaria"
  /M49D     "During pregnancy took: Quinine for malaria"
  /M49E     "NA - During pregnancy took: CS drug for malaria"
  /M49F     "NA - During pregnancy took: CS drug for malaria"
  /M49G     "NA - During pregnancy took: CS drug for malaria"
  /M49X     "During pregnancy took: other drug for malaria"
  /M49Z     "During pregnancy took: don't know"
  /M49Y     "During pregnancy took: no drug for malaria"
  /M50      "Respondent's check up after delivery"
  /M51      "Respondent's checkup after deliver timing"
  /M52      "Respondent's health professional checked up after delivery"
  /M54      "Received Vitamin A dose in first 2 months after delivery"
  /M55A     "First 3 days, given milk (other than breast milk)"
  /M55B     "First 3 days, given plain water"
  /M55C     "First 3 days, given sugar/glucose water"
  /M55D     "First 3 days, given gripe water"
  /M55E     "First 3 days, given sugar/salt solution"
  /M55F     "First 3 days, given fruit juice"
  /M55G     "First 3 days, given infant formula"
  /M55H     "First 3 days, given tea/infusions"
  /M55I     "First 3 days, given honey"
  /M55J     "First 3 days, given coffee"
  /M55K     "NA - First 3 days, given country specific"
  /M55L     "NA - First 3 days, given country specific"
  /M55M     "NA - First 3 days, given country specific"
  /M55N     "NA - First 3 days, given country specific"
  /M55O     "NA - First 3 days, given country specific"
  /M55X     "First 3 days, given other"
  /M55Z     "First 3 days, given nothing"
  /M57A     "Antenatal care: respondent's home"
  /M57B     "Antenatal care: other home"
  /M57C     "NA - Antenatal care: CS home"
  /M57D     "NA - Antenatal care: CS home"
  /M57E     "Antenatal care: government hospital"
  /M57F     "Antenatal care: provincial/district hospital"
  /M57G     "Antenatal care: health center"
  /M57H     "Antenatal care: health post"
  /M57I     "Antenatal care: other public facility"
  /M57J     "NA - Antenatal care: CS public health"
  /M57K     "NA - Antenatal care: CS public health"
  /M57L     "NA - Antenatal care: CS public health"
  /M57M     "Antenatal care: clinic"
  /M57N     "Antenatal care: polyclinic"
  /M57O     "Antenatal care: dispensary"
  /M57P     "Antenatal care: other private medical"
  /M57Q     "NA - Antenatal care: CS private medical"
  /M57R     "NA - Antenatal care: CS private medical"
  /M57S     "NA - Antenatal care: CS other"
  /M57T     "NA - Antenatal care: CS other"
  /M57U     "NA - Antenatal care: CS other"
  /M57V     "NA - Antenatal care: CS other"
  /M57X     "Antenatal care: other"
  /M60      "Drugs for intestinal parasites during pregnancy"
  /M61      "NA - Time spent at place of delivery"
  /M62      "Respondent's health checked before discharge"
  /M65A     "NA - Reason didn't deliver at health facility: cost too much"
  /M65B     "NA - Reason didn't deliver at health facility: facility not open"
  /M65C     "NA - Reason didn't deliver at health facility: too far/no transport"
  /M65D     "NA - Reason didn't deliver at health facility: don't trust facility/poor service"
  /M65E     "NA - Reason didn't deliver at health facility: no female provider"
  /M65F     "NA - Reason didn't deliver at health facility: husband/family didn't allow"
  /M65G     "NA - Reason didn't deliver at health facility: not necessary"
  /M65H     "NA - Reason didn't deliver at health facility: not customary"
  /M65I     "NA - Reason didn't deliver at health facility: CS"
  /M65J     "NA - Reason didn't deliver at health facility: CS"
  /M65K     "NA - Reason didn't deliver at health facility: CS"
  /M65L     "NA - Reason didn't deliver at health facility: CS"
  /M65X     "NA - Reason didn't deliver at health facility: other"
  /M66      "Respondent's health checked after discharge/delivery at home"
  /M70      "Baby postnatal check within 2 months"
  /M71      "Time after delivery postnatal check took place"
  /M72      "Person who performed postnatal checkup"
  /M73      "Place baby was first checked"
  /HIDX     "Index to birth history"
  /H1       "Has health card"
  /H2       "Received BCG"
  /H2D      "BCG day"
  /H2M      "BCG month"
  /H2Y      "BCG year"
  /H3       "Received Pentavalent 1"
  /H3D      "Pentavalent 1 day"
  /H3M      "Pentavalent 1 month"
  /H3Y      "Pentavalent 1 year"
  /H4       "Received Polio 1"
  /H4D      "Polio 1 day"
  /H4M      "Polio 1 month"
  /H4Y      "Polio 1 year"
  /H5       "Received Pentavalent 2"
  /H5D      "Pentavalent 2 day"
  /H5M      "Pentavalent 2 month"
  /H5Y      "Pentavalent 2 year"
  /H6       "Received Polio 2"
  /H6D      "Polio 2 day"
  /H6M      "Polio 2 month"
  /H6Y      "Polio 2 year"
  /H7       "Received Pentavalent 3"
  /H7D      "Pentavalent 3 day"
  /H7M      "Pentavalent 3 month"
  /H7Y      "Pentavalent 3 year"
  /H8       "Received Polio 3"
  /H8D      "Polio 3 day"
  /H8M      "Polio 3 month"
  /H8Y      "Polio 3 year"
  /H9       "Received Measles"
  /H9D      "Measles day"
  /H9M      "Measles month"
  /H9Y      "Measles year"
  /H0       "Received Polio 0"
  /H0D      "Polio 0 day"
  /H0M      "Polio 0 month"
  /H0Y      "Polio 0 year"
  /H10      "Ever had vaccination"
  /H11      "Had diarrhea recently"
  /H11B     "Blood in the stools"
  /H12A     "Diarrhea: government hospital"
  /H12B     "Diarrhea: provincial / district hospital"
  /H12C     "Diarrhea: health center"
  /H12D     "Diarrhea: CS health post"
  /H12E     "Diarrhea: CS outreach"
  /H12F     "Diarrhea: CS community health worker"
  /H12G     "NA - Diarrhea: CS public sector"
  /H12H     "NA - Diarrhea: CS public sector"
  /H12I     "Diarrhea: CS other public facility"
  /H12J     "Diarrhea: private hospital/clinic"
  /H12K     "Diarrhea: private pharmacy"
  /H12L     "NA - Diarrhea: private doctor"
  /H12M     "Diarrhea: polyclinic"
  /H12N     "Diarrhea: dispensary"
  /H12O     "NA - Diarrhea: CS private medical"
  /H12P     "Diarrhea: other private medical facility"
  /H12Q     "NA - Diarrhea: CS private medical"
  /H12R     "NA - Diarrhea: CS private medical"
  /H12S     "Diarrhea: kiosk / shop"
  /H12T     "Diarrhea: traditional healer"
  /H12U     "Diarrhea: church"
  /H12V     "Diarrhea: friend / relative"
  /H12W     "NA - Diarrhea: CS other sector"
  /H12X     "Diarrhea: Other"
  /H12Y     "Diarrhea: no treatment"
  /H12Z     "Diarrhea: medical treatment"
  /H13      "Given oral rehydration"
  /H13B     "NA - Given pre-packaged ORS liquid"
  /H14      "Given recommended home solution"
  /H15      "Given antibiotic pills or syrups"
  /H15A     "Given antimotility"
  /H15B     "Given antibiotic injection"
  /H15C     "Given intravenous (IV)"
  /H15D     "Given home remedy, herbal medicine"
  /H15E     "NA - Given zinc"
  /H15F     "Given other (not antibiotic, antimotility, zinc)"
  /H15G     "Given unknown pill or syrup"
  /H15H     "Given non-antibiotic injection"
  /H15I     "Given unknown injection"
  /H15J     "NA - Given CS"
  /H15K     "NA - Given CS"
  /H15L     "NA - Given CS"
  /H15M     "NA - Given CS"
  /H20      "Given other treatment"
  /H21A     "Given no treatment"
  /H21      "Received any treatment"
  /H22      "Had fever in last two weeks"
  /H31      "Had cough in last two weeks"
  /H31B     "Short, rapid breaths"
  /H31C     "Problem in the chest or blocked or running nose"
  /H31D     "Had fever/cough in last 2 weeks: amount offered to drink"
  /H31E     "Had fever/cough in last 2 weeks: amount offered to eat"
  /H32A     "Fever/cough: government hospital"
  /H32B     "Fever/cough: provincial / district hospital"
  /H32C     "Fever/cough: health center"
  /H32D     "Fever/cough: health post"
  /H32E     "Fever/cough: outreach"
  /H32F     "Fever/cough: community health worker"
  /H32G     "NA - Fever/cough: CS public sector"
  /H32H     "NA - Fever/cough: CS public sector"
  /H32I     "Fever/cough: other public facility"
  /H32J     "Fever/cough: clinic"
  /H32K     "Fever/cough: pharmacy"
  /H32L     "NA - Fever/cough: private doctor"
  /H32M     "Fever/cough: polyclinic"
  /H32N     "Fever/cough: dispensary"
  /H32O     "NA - Fever/cough: CS private medical"
  /H32P     "Fever/cough: other private facility"
  /H32Q     "NA - Fever/cough: CS private medical"
  /H32R     "NA - Fever/cough: CS private medical"
  /H32S     "Fever/cough: kiosk / shop"
  /H32T     "Fever/cough: traditional healer"
  /H32U     "Fever/cough: church"
  /H32V     "Fever/cough: friend / relative"
  /H32W     "NA - Fever/cough: CS other sector"
  /H32X     "Fever/cough: other"
  /H32Y     "Fever/cough: no treatment"
  /H32Z     "Fever/cough: medical treatment"
  /H33      "Received Vitamin A1 (most recent)"
  /H33D     "Vitamin A1 day"
  /H33M     "Vitamin A1 month"
  /H33Y     "Vitamin A1 year"
  /H34      "Vitamin A in last 6 months"
  /H35      "NA - Any vaccinations in last 2 years part of campaign"
  /H36A     "NA - Vaccinated during Campaign A"
  /H36B     "NA - Vaccinated during Campaign B"
  /H36C     "NA - Vaccinated during Campaign C"
  /H36D     "NA - Vaccinated during Campaign D"
  /H36E     "NA - Vaccinated during Campaign E"
  /H36F     "NA - Vaccinated during Campaign F"
  /H37A     "NA - SP/Fansidar taken for fever/cough"
  /H37B     "NA - Chloroquine taken for fever/cough"
  /H37C     "NA - Amodiaquine taken for fever/cough"
  /H37D     "NA - Quinine taken for fever/cough"
  /H37E     "NA - Combination with artemisinin taken for fever/cough"
  /H37F     "NA - CS antimalarial taken for fever/cough"
  /H37G     "NA - CS antimalarial taken for fever/cough"
  /H37H     "NA - Other antimalarial taken for fever/cough"
  /H37I     "NA - Antibiotic pill/syrup taken for fever/cough"
  /H37J     "NA - Antibiotic injection taken for fever/cough"
  /H37K     "NA - Aspirin taken for fever/cough"
  /H37L     "NA - Acetaminophen/paracetamol/panadol taken for fever/cough"
  /H37M     "NA - Ibuprofen taken for fever/cough"
  /H37N     "NA - CS other taken for fever/cough"
  /H37O     "NA - CS other for fever/cough"
  /H37P     "NA - CS other for fever/cough"
  /H37X     "NA - Other taken for fever/cough"
  /H37Y     "NA - Nothing taken for fever/cough"
  /H37Z     "NA - Don't know if or what was taken for fever/cough"
  /H38      "Diarrhea in last 2 weeks: amount offered to drink"
  /H39      "Diarrhea in last 2 weeks: amount offered to eat"
  /H40      "NA - Received Vitamin A2 (2nd most recent)"
  /H40D     "NA - Vitamin A2 day"
  /H40M     "NA - Vitamin A2 month"
  /H40Y     "NA - Vitamin A2 year"
  /H41A     "NA - Received vitamin A after most recent in card"
  /H41B     "NA - Ever received Vitamin A dose"
  /H42      "NA - Taking iron pills, sprinkles or syrup"
  /H43      "Drugs for intestinal parasites in last 6 months"
  /H44A     "Place first sought treatment for diarrhea"
  /H44B     "NA - Days after diarrhea sought advice or treatment"
  /H44C     "NA - Still has diarrhea"
  /H45      "NA - Times zinc was given"
  /H46A     "Place first sought treatment for fever"
  /H46B     "NA - Days after fever sought advice or treatment"
  /H47      "Blood taken from child's finger/heel for testing"
  /HWIDX    "Index to Birth History"
  /HW1      "Child's age in months"
  /HW2      "Child's weight in kilograms (1 decimal)"
  /HW3      "Child's height in centimeters (1 decimal)"
  /HW4      "Height/Age percentile"
  /HW5      "Height/Age standard deviation"
  /HW6      "Height/Age percent of ref. median"
  /HW7      "Weight/Age percentile"
  /HW8      "Weight/Age standard deviation"
  /HW9      "Weight/Age percent of ref. median"
  /HW10     "Weight/Height percentile"
  /HW11     "Weight/Height standard deviation"
  /HW12     "Weight/Height percent of ref. median"
  /HW13     "Result of measurement - height/weight"
  /HW15     "Height: lying or standing"
  /HW16     "Day of birth of child"
  /HW17     "Date measured (day)"
  /HW18     "Date measured (month)"
  /HW19     "Date measured (year)"
  /HW51     "Line number of parent/caretaker"
  /HW52     "Read consent statement - hemoglobin"
  /HW53     "Hemoglobin level (g/dl - 1 decimal)"
  /HW55     "Result of measurement - hemoglobin"
  /HW56     "Hemoglobin level adjusted for altitude (g/dl - 1 decimal)"
  /HW57     "Anemia level"
  /HW58     "NA - Agrees to referral - anemia"
  /HW70     "Height/Age standard deviation (new WHO)"
  /HW71     "Weight/Age standard deviation (new WHO)"
  /HW72     "Weight/Height standard deviation (new WHO)"
  /HW73     "BMI standard deviation (new WHO)"
  /IDXML    "Index to Birth History"
  /ML0      "Type of mosquito bed net(s) child slept under last night"
  /ML1      "NA - Number of times took fansidar during pregnancy"
  /ML2      "NA - Source of antimalarial during pregnancy"
  /ML11     "NA - Child has fever/cough now"
  /ML12     "NA - Child has had convulsions in last 2 weeks"
  /ML13A    "NA - Fansidar taken for fever/cough"
  /ML13B    "NA - Chloroquine taken for fever/cough"
  /ML13C    "NA - Amodiaquine taken for fever/cough"
  /ML13D    "Quinine taken for fever/cough"
  /ML13E    "Coartem - combination with artemisinin taken for fever/cough"
  /ML13F    "Primo"
  /ML13G    "NA - CS antimalarial taken for fever/cough"
  /ML13H    "Other antimalarial taken for fever/cough"
  /ML13I    "Antibiotic pill/syrup taken for fever/cough"
  /ML13J    "Antibiotic injection taken for fever/cough"
  /ML13K    "Aspirin taken for fever/cough"
  /ML13L    "Acetaminophen/paracetamol/panadol taken for fever/cough"
  /ML13M    "Ibuprofen taken for fever/cough"
  /ML13N    "Homemade medicine for fever/cough"
  /ML13O    "NA - CS other taken for fever/co"
  /ML13P    "NA - CS other taken for fever/cough"
  /ML13X    "Other taken for fever/cough"
  /ML13Y    "Nothing taken for fever/cough"
  /ML13Z    "Don't know if or what was taken for fever/cough"
  /ML14A    "NA - Injection given for fever/convulsion***"
  /ML14B    "NA - Suppository given for fever/convulsion***"
  /ML14Y    "NA - No suppository or injection given for fever/convulsion***"
  /ML14Z    "NA - Don't know if suppository or injection given for fever/convulsion***"
  /ML15A    "NA - Timing of start of fansidar"
  /ML15B    "NA - Number of days child took fansidar"
  /ML15C    "NA - First source for fansidar"
  /ML16A    "NA - Timing of start of chloroquine"
  /ML16B    "NA - Number of days child took chloroquine"
  /ML16C    "NA - First source for chloroquine"
  /ML17A    "NA - Timing of start of amodiaquine"
  /ML17B    "NA - Number of days child took amodiaquine"
  /ML17C    "NA - First source for amodiaquine"
  /ML18A    "Timing of start of quinine"
  /ML18B    "NA - Number of days child took quinine"
  /ML18C    "NA - First source for quinine"
  /ML19A    "NA - For fever/convulsion: consulted traditional healer***"
  /ML19B    "NA - For fever/convulsion: gave tepid sponging***"
  /ML19C    "NA - For fever/convulsion: gave herbs***"
  /ML19D    "NA - For fever/convulsion: CS***"
  /ML19E    "NA - For fever/convulsion: CS***"
  /ML19F    "NA - For fever/convulsion: CS***"
  /ML19X    "NA - For fever/convulsion: other***"
  /ML19Y    "NA - For fever/convulsion: gave/did nothing***"
  /ML19Z    "NA - For fever/convulsion: don't know if something else was done***"
  /ML20A    "Timing of start of Coartem"
  /ML20B    "NA - Number of days child took combination with artemisinin"
  /ML20C    "NA - First source for combination with artemisinin"
  /ML21A    "Timing of start of Primo"
  /ML21B    "NA - Number of days child took CS antimalarial"
  /ML21C    "NA - First source for CS antimalarial"
  /ML22A    "NA - Timing of start of CS antimalarial use"
  /ML22B    "NA - Number of days child took CS antimalarial"
  /ML22C    "NA - First source for CS antimalarial"
  /ML23A    "Timing of start of other anti-malarial use"
  /ML23B    "NA - Number of days child took other anti-malarial"
  /ML23C    "NA - First source for other anti-malarial"
  /ML24C    "NA - First source for antibiotic pill/syrup"
  /SLANG    "Language of the interview"
  /STRANS   "Translator used"
  /SDISTRICT "District"
  /S105     "Highest educational level"
  /S106     "Highest grade/form/year at that level"
  /S106A    "Highest educational level - report"
  /S115     "Number of trips in last 12 months"
  /S205CA   "Where do sons or daughters live - boarding school"
  /S205CB   "Where do sons or daughters live - relative"
  /S205CC   "Where do sons or daughters live - in the street"
  /S205CD   "Where do sons or daughters live - work"
  /S205CE   "Where do sons or daughters live - married"
  /S205CX   "Where do sons or daughters live - other"
  /S205CZ   "Where do sons or daughters live - don't know"
  /S564     "Line number of child"
  /S564A    "Line number of child - youngest"
  /S566     "Number of children's books"
  /S567A    "Does child play with homemade toys"
  /S567B    "Does child play with toys from store"
  /S567C    "Does child play with household objects"
  /S568A    "Number of times left alone for more than an hour during last week"
  /S568B    "Number of times left with another child for more than an hour during last week"
  /S570     "Line number of child ages 0-5"
  /S570A    "Line number of child ages 3-5"
  /S572     "Attend any organized learning or early childhood education program"
  /S573     "Number of hours spent in last 7 days"
  /S574AA   "Mom read books to child"
  /S574AB   "Dad read books to child"
  /S574AX   "Other person read books to child"
  /S574AY   "No one read books to child"
  /S574BA   "Mom told stories to child"
  /S574BB   "Dad told stories to child"
  /S574BX   "Other person told stories to child"
  /S574BY   "No one told stories to child"
  /S574CA   "Mom sang songs to child"
  /S574CB   "Dad sang songs to child"
  /S574CX   "Other person sang songs to child"
  /S574CY   "No one sang songs to child"
  /S574DA   "Mom took child outside"
  /S574DB   "Dad took child outside"
  /S574DX   "Other person took child outside"
  /S574DY   "No one took child outside"
  /S574EA   "Mom played with child"
  /S574EB   "Dad played with child"
  /S574EX   "Other person played with child"
  /S574EY   "No one played with child"
  /S574FA   "Mom named, counted, or drew things with the child"
  /S574FB   "Dad named, counted, or drew things with the child"
  /S574FX   "Other person named, counted, or drew things with the child"
  /S574FY   "No one named, counted, or drew things with the child"
  /S575     "Can child identify or name at least ten letters of the alphabet"
  /S576     "Can child read at least four simple, popular words"
  /S577     "Does child know name and recognize symbol of all numbers from 1 to 10"
  /S578     "Can child pick up a small object with two fingers"
  /S579     "Is child sometimes too sick to play"
  /S580     "Does child follow simple instructions"
  /S581     "Is child able to do somethings independently"
  /S582     "Does child get along well with other children"
  /S583     "Does child kick, bite, or hit other children or adults"
  /S584     "Does child get distracted easily"
  /S623A    "Number of times in the last month had sexual intercourse with last partner"
  /S623B    "Number of times in the last month had sexual intercourse with second to last partner"
  /S623C    "Number of times in the last month had sexual intercourse with third to last partner"
  /S626A    "For women reporting 3 partners in last year the total number of people had sex with in the last month"
  /S714D    "Read about family planning in a brochure/pamphlet"
  /S826E    "Justified beating his wife when she has sex with someone else"
  /S827A    "Justified beating child if he/she disobeys"
  /S827B    "Justified beating child if he/she is impolite"
  /S827C    "Justified beating child if he/she embarrasses the family"
  /S907A    "Men reduce chances on AIDS by getting circumcised"
  /S910B    "Tested for AIDS for prenuptial purposes"
  /S910D    "Tested for AIDS as a couple"
  /S910E    "Tested for AIDS told each other results"
  /S1011A   "Have the following symptom - cough"
  /S1011B   "Have the following symptom - fever"
  /S1011C   "Have the following symptom - drenching nights sweats"
  /S1011D   "Have the following symptom - unexpected weight loss"
  /S1011E   "Have the following symptom - general fatigue or malaise"
  /S1011F   "Have the following symptom - chest pain"
  /S1013    "Have you ever sought help or care for symptom(s)"
  /S1014A   "Sought advice/treatment from: referral hospital"
  /S1014B   "Sought advice/treatment from: provincial/district hospital"
  /S1014C   "Sought advice/treatment from: health center"
  /S1014D   "Sought advice/treatment from: health post"
  /S1014E   "Sought advice/treatment from: outreach"
  /S1014F   "Sought advice/treatment from: community health worker"
  /S1014I   "Sought advice/treatment from: other public health facility"
  /S1014J   "Sought advice/treatment from: clinic"
  /S1014K   "Sought advice/treatment from: pharmacy"
  /S1014M   "Sought advice/treatment from: polyclinic"
  /S1014N   "Sought advice/treatment from: dispensary"
  /S1014O   "Sought advice/treatment from: family planning clinic"
  /S1014P   "Sought advice/treatment from: other private health facility"
  /S1014S   "Sought advice/treatment from: kiosk, shop, bar"
  /S1014T   "Sought advice/treatment from: traditional healer"
  /S1014V   "Sought advice/treatment from: friend, relative"
  /S1014X   "Sought advice/treatment from: other"
  /SDV18    "Person or persons physically hurt you in the last 12 months"
  /SDV18C   "Main person (besides husband/partner) who hurt respondent in last 12 months"
  /SDV24    "Anyone (besides husband/partner) forced respondent to have intercourse in last 12 months"
  /SDV24A   "Person (besides husband/partner) who forced respondent the very first time to have intercourse in last 12 months"
  /IDX94    "Index to Birth History"
  /S412B    "Months pregnant at second antenatal care"
  /S412D    "Months pregnant at third antenatal care"
  /S412F    "Months pregnant at fourth antenatal care"
  /S425AA   "Where got antimalarial drug - reference hospital"
  /S425AB   "Where got antimalarial drug - district hospital"
  /S425AC   "Where got antimalarial drug - health center"
  /S425AD   "Where got antimalarial drug - health post"
  /S425AE   "Where got antimalarial drug - outreach"
  /S425AF   "Where got antimalarial drug - health worker"
  /S425AI   "Where got antimalarial drug - other public facility"
  /S425AJ   "Where got antimalarial drug - clinic"
  /S425AK   "Where got antimalarial drug - pharmacy"
  /S425AM   "Where got antimalarial drug - polyclinic"
  /S425AN   "Where got antimalarial drug - dispensary"
  /S425AP   "Where got antimalarial drug - other private facility"
  /S425AS   "Where got antimalarial drug - kiosk"
  /S425AT   "Where got antimalarial drug - traditional healer"
  /S425AU   "Where got antimalarial drug - church"
  /S425AV   "Where got antimalarial drug - friend relative"
  /S425AX   "Where got antimalarial drug - other"
  /S435A    "How traveled to health facility to deliver by Caesarean"
  /S452U    "Time without sexual intercourse - unit"
  /S452N    "Time without sexual intercourse - number"
  /S460B    "Why delivered at home"
  /IDX95    "Index to Birth History"
  /S506N1   "Received Pneumococcal 1"
  /S506N1D  "Pneumococcal 1 day"
  /S506N1M  "Pneumococcal 1 month"
  /S506N1Y  "Pneumococcal 1 year"
  /S506N2   "Received Pneumococcal 2"
  /S506N2D  "Pneumococcal 2 day"
  /S506N2M  "Pneumococcal 2 month"
  /S506N2Y  "Pneumococcal 2 year"
  /S506N3   "Received Pneumococcal 3"
  /S506N3D  "Pneumococcal 3 day"
  /S506N3M  "Pneumococcal 3 month"
  /S506N3Y  "Pneumococcal 3 year"
  /S506R1   "Received Rotavirus 1"
  /S506R1D  "Rotavirus 1 day"
  /S506R1M  "Rotavirus 1  month"
  /S506R1Y  "Rotavirus 1 year"
  /S506R2   "Received Rotavirus 2"
  /S506R2D  "Rotavirus 2 day"
  /S506R2M  "Rotavirus 2  month"
  /S506R2Y  "Rotavirus 2 year"
  /S506R3   "Received Rotavirus 3"
  /S506R3D  "Rotavirus 3 day"
  /S506R3M  "Rotavirus 3  month"
  /S506R3Y  "Rotavirus 3 year"
  /S506MR   "Received MMR"
  /S506MRD  "MMR day"
  /S506MRM  "MMR month"
  /S506MRY  "MMR year"
  /S517B    "Continue to breastfeed while he/she had diarrhea (last birth only)"
  /S561A    "Heard of counseling or education on nutrition"
  /S561BA   "Where did hear about nutritional education - health facility"
  /S561BB   "Where did hear about nutritional education - community health worker"
  /S561BC   "Where did hear about nutritional education - friends/relatives"
  /S561BD   "Where did hear about nutritional education - magazine/newspaper/radio/TV"
  /S561BX   "Where did hear about nutritional education - other"
 .
MISSING VALUE
   V026     (9)
  /V027     (9)
  /V028     (999)
  /V029     (99)
  /V030     (999)
  /V031     (999)
  /V032     (99)
  /V034     (99)
  /V040     (9999)
  /V103     (9)
  /V104     (99)
  /V105     (9)
  /V106     (9)
  /V107     (99)
  /V113     (99)
  /V115     (999)
  /V116     (99)
  /V119     (9)
  /V120     (9)
  /V121     (9)
  /V122     (9)
  /V123     (9)
  /V124     (9)
  /V125     (9)
  /V127     (99)
  /V128     (99)
  /V129     (99)
  /V130     (99)
  /V131     (999)
  /V133     (99)
  /V134     (9)
  /V135     (9)
  /V139     (99)
  /V140     (9)
  /V141     (9)
  /V149     (9)
  /V150     (99)
  /V152     (99)
  /V153     (9)
  /V155     (9)
  /V156     (9)
  /V157     (9)
  /V158     (9)
  /V159     (9)
  /V160     (9)
  /V161     (99)
  /V166     (999)
  /V167     (99)
  /V168     (9)
  /ML101    (9)
  /V215     (999)
  /V217     (9)
  /V225     (9)
  /V226     (999)
  /V228     (9)
  /V229     (99)
  /V230     (9999)
  /V231     (9999)
  /V233     (99)
  /V234     (9)
  /V237     (9)
  /V239     (9)
  /V240     (99)
  /V241     (9999)
  /V242     (9999)
  /V310     (99)
  /V311     (9)
  /V312     (99)
  /V313     (9)
  /V323     (99)
  /V323A    (99)
  /V325A    (9999999)
  /V326     (99)
  /V327     (9)
  /V337     (999)
  /V359     (99)
  /V360     (99)
  /V362     (9)
  /V363     (99)
  /V367     (9)
  /V372     (9)
  /V372A    (9)
  /V375A    (99)
  /V376     (99)
  /V376A    (9)
  /V379     (99)
  /V380     (9)
  /V384A    (9)
  /V384B    (9)
  /V384C    (9)
  /V393     (9)
  /V394     (9)
  /V395     (9)
  /V3A00A   (9)
  /V3A00B   (9)
  /V3A00C   (9)
  /V3A00D   (9)
  /V3A00E   (9)
  /V3A00F   (9)
  /V3A00G   (9)
  /V3A00H   (9)
  /V3A00I   (9)
  /V3A00J   (9)
  /V3A00K   (9)
  /V3A00L   (9)
  /V3A00M   (9)
  /V3A00N   (9)
  /V3A00O   (9)
  /V3A00P   (9)
  /V3A00Q   (9)
  /V3A00R   (9)
  /V3A00S   (9)
  /V3A00T   (9)
  /V3A00U   (9)
  /V3A00V   (9)
  /V3A00W   (9)
  /V3A00X   (9)
  /V3A00Y   (9)
  /V3A00Z   (9)
  /V3A01    (9)
  /V3A02    (9)
  /V3A03    (9)
  /V3A04    (9)
  /V3A05    (9)
  /V3A06    (9)
  /V3A07    (99)
  /V3A08A   (9)
  /V3A08B   (9)
  /V3A08C   (9)
  /V3A08D   (9)
  /V3A08E   (9)
  /V3A08F   (9)
  /V3A08G   (9)
  /V3A08H   (9)
  /V3A08I   (9)
  /V3A08J   (9)
  /V3A08K   (9)
  /V3A08L   (9)
  /V3A08M   (9)
  /V3A08N   (9)
  /V3A08O   (9)
  /V3A08P   (9)
  /V3A08Q   (9)
  /V3A08R   (9)
  /V3A08S   (9)
  /V3A08T   (9)
  /V3A08U   (9)
  /V3A08V   (9)
  /V3A08W   (9)
  /V3A08AA  (9)
  /V3A08AB  (9)
  /V3A08AC  (9)
  /V3A08AD  (9)
  /V3A08X   (9)
  /V3A08Z   (9)
  /V3A09A   (999)
  /V3A09B   (999)
  /V401     (9)
  /V407     (99)
  /V408     (99)
  /V409     (9)
  /V409A    (9)
  /V410     (9)
  /V410A    (9)
  /V411     (9)
  /V411A    (9)
  /V412     (9)
  /V412A    (9)
  /V412B    (9)
  /V412C    (9)
  /V413     (9)
  /V413A    (9)
  /V413B    (9)
  /V413C    (9)
  /V413D    (9)
  /V414A    (9)
  /V414B    (9)
  /V414C    (9)
  /V414D    (9)
  /V414E    (9)
  /V414F    (9)
  /V414G    (9)
  /V414H    (9)
  /V414I    (9)
  /V414J    (9)
  /V414K    (9)
  /V414L    (9)
  /V414M    (9)
  /V414N    (9)
  /V414O    (9)
  /V414P    (9)
  /V414Q    (9)
  /V414R    (9)
  /V414S    (9)
  /V414T    (9)
  /V414U    (9)
  /V414V    (9)
  /V414W    (9)
  /V415     (9)
  /V416     (9)
  /V420     (999)
  /V421     (999)
  /V426     (999)
  /V437     (9999)
  /V438     (9999)
  /V439     (9999)
  /V440     (9999)
  /V441     (99999)
  /V442     (99999)
  /V443     (99999)
  /V444     (99999)
  /V444A    (9999)
  /V445     (9999)
  /V446     (9999)
  /V447     (9)
  /V452A    (9)
  /V452B    (99)
  /V452C    (9)
  /V453     (999)
  /V454     (9)
  /V455     (9)
  /V456     (999)
  /V457     (9)
  /V458     (9)
  /V459     (9)
  /V460     (9)
  /V461     (9)
  /V462     (9)
  /V463A    (9)
  /V463B    (9)
  /V463C    (9)
  /V463D    (9)
  /V463E    (9)
  /V463F    (9)
  /V463G    (9)
  /V463X    (9)
  /V463Z    (9)
  /V464     (99)
  /V465     (99)
  /V466     (9)
  /V467A    (9)
  /V467B    (9)
  /V467C    (9)
  /V467D    (9)
  /V467E    (9)
  /V467F    (9)
  /V467G    (9)
  /V467H    (9)
  /V467I    (9)
  /V467J    (9)
  /V467K    (9)
  /V467L    (9)
  /V467M    (9)
  /V469E    (9)
  /V469F    (9)
  /V469X    (9)
  /V471A    (9)
  /V471B    (9)
  /V471C    (9)
  /V471D    (9)
  /V471E    (9)
  /V471F    (9)
  /V471G    (9)
  /V472A    (9)
  /V472B    (9)
  /V472C    (9)
  /V472D    (9)
  /V472E    (9)
  /V472F    (9)
  /V472G    (9)
  /V472H    (9)
  /V472I    (9)
  /V472J    (9)
  /V472K    (9)
  /V472L    (9)
  /V472M    (9)
  /V472N    (9)
  /V472O    (9)
  /V472P    (9)
  /V472Q    (9)
  /V472R    (9)
  /V472S    (9)
  /V472T    (9)
  /V472U    (9)
  /V473A    (9)
  /V473B    (9)
  /V474     (9)
  /V474A    (9)
  /V474B    (9)
  /V474C    (9)
  /V474D    (9)
  /V474E    (9)
  /V474F    (9)
  /V474G    (9)
  /V474H    (9)
  /V474I    (9)
  /V474J    (9)
  /V474K    (9)
  /V474X    (9)
  /V474Z    (9)
  /V475     (9)
  /V476     (9)
  /V477     (99)
  /V478     (99)
  /V479     (99)
  /V480     (9)
  /V481     (9)
  /V481A    (9)
  /V481B    (9)
  /V481C    (9)
  /V481D    (9)
  /V481E    (9)
  /V481F    (9)
  /V481G    (9)
  /V481H    (9)
  /V481X    (9)
  /V482A    (9)
  /V482B    (9)
  /V482C    (9)
  /V501     (9)
  /V502     (9)
  /V503     (9)
  /V504     (9)
  /V505     (99)
  /V506     (99)
  /V525     (99)
  /V527     (999)
  /V528     (99)
  /V529     (999)
  /V531     (99)
  /V535     (9)
  /V536     (9)
  /V537     (99)
  /V538     (9)
  /V539     (9)
  /V540     (9)
  /V541     (9)
  /V602     (9)
  /V603     (999)
  /V604     (9)
  /V605     (9)
  /V613     (99)
  /V616     (999)
  /V621     (9)
  /V623     (9)
  /V624     (99)
  /V625     (9)
  /V626     (99)
  /V625A    (9)
  /V626A    (99)
  /V627     (99)
  /V628     (99)
  /V629     (99)
  /V631     (9)
  /V632     (9)
  /V633A    (9)
  /V633B    (9)
  /V633C    (9)
  /V633D    (9)
  /V633E    (9)
  /V633F    (9)
  /V633G    (9)
  /V634     (9)
  /V701     (9)
  /V702     (99)
  /V704     (999)
  /V705     (99)
  /V714     (9)
  /V714A    (9)
  /V715     (99)
  /V716     (999)
  /V717     (99)
  /V719     (9)
  /V721     (9)
  /V729     (9)
  /V730     (99)
  /V731     (9)
  /V732     (9)
  /V739     (9)
  /V740     (9)
  /V741     (9)
  /V743A    (9)
  /V743B    (9)
  /V743C    (9)
  /V743D    (9)
  /V743E    (9)
  /V743F    (9)
  /V744A    (9)
  /V744B    (9)
  /V744C    (9)
  /V744D    (9)
  /V744E    (9)
  /V745A    (9)
  /V745B    (9)
  /V746     (9)
  /B6       (999)
  /B9       (9)
  /B15      (9)
  /B16      (99)
  /M1       (9)
  /M1A      (9)
  /M1B      (99)
  /M1C      (9999)
  /M1D      (99)
  /M2A      (9)
  /M2B      (9)
  /M2C      (9)
  /M2D      (9)
  /M2E      (9)
  /M2F      (9)
  /M2G      (9)
  /M2H      (9)
  /M2I      (9)
  /M2J      (9)
  /M2K      (9)
  /M2L      (9)
  /M2M      (9)
  /M2N      (9)
  /M3A      (9)
  /M3B      (9)
  /M3C      (9)
  /M3D      (9)
  /M3E      (9)
  /M3F      (9)
  /M3G      (9)
  /M3H      (9)
  /M3I      (9)
  /M3J      (9)
  /M3K      (9)
  /M3L      (9)
  /M3M      (9)
  /M3N      (9)
  /M4       (99)
  /M5       (99)
  /M6       (99)
  /M7       (99)
  /M8       (99)
  /M9       (99)
  /M10      (9)
  /M11      (999)
  /M13      (99)
  /M14      (99)
  /M15      (99)
  /M17      (9)
  /M18      (9)
  /M19      (9999)
  /M34      (999)
  /M35      (99)
  /M36      (99)
  /M38      (9)
  /M39A     (9)
  /M39      (9)
  /M42A     (9)
  /M42B     (9)
  /M42C     (9)
  /M42D     (9)
  /M42E     (9)
  /M43      (9)
  /M44      (9)
  /M45      (9)
  /M46      (999)
  /M47      (9)
  /M48      (9)
  /M49A     (9)
  /M49B     (9)
  /M49C     (9)
  /M49D     (9)
  /M49E     (9)
  /M49F     (9)
  /M49G     (9)
  /M49X     (9)
  /M49Z     (9)
  /M49Y     (9)
  /M50      (9)
  /M51      (999)
  /M52      (99)
  /M54      (9)
  /M55A     (9)
  /M55B     (9)
  /M55C     (9)
  /M55D     (9)
  /M55E     (9)
  /M55F     (9)
  /M55G     (9)
  /M55H     (9)
  /M55I     (9)
  /M55J     (9)
  /M55K     (9)
  /M55L     (9)
  /M55M     (9)
  /M55N     (9)
  /M55O     (9)
  /M55X     (9)
  /M55Z     (9)
  /M57A     (9)
  /M57B     (9)
  /M57C     (9)
  /M57D     (9)
  /M57E     (9)
  /M57F     (9)
  /M57G     (9)
  /M57H     (9)
  /M57I     (9)
  /M57J     (9)
  /M57K     (9)
  /M57L     (9)
  /M57M     (9)
  /M57N     (9)
  /M57O     (9)
  /M57P     (9)
  /M57Q     (9)
  /M57R     (9)
  /M57S     (9)
  /M57T     (9)
  /M57U     (9)
  /M57V     (9)
  /M57X     (9)
  /M60      (9)
  /M61      (999)
  /M62      (9)
  /M65A     (9)
  /M65B     (9)
  /M65C     (9)
  /M65D     (9)
  /M65E     (9)
  /M65F     (9)
  /M65G     (9)
  /M65H     (9)
  /M65I     (9)
  /M65J     (9)
  /M65K     (9)
  /M65L     (9)
  /M65X     (9)
  /M66      (9)
  /M70      (9)
  /M71      (999)
  /M72      (99)
  /M73      (99)
  /H1       (9)
  /H2       (9)
  /H2D      (99)
  /H2M      (99)
  /H2Y      (9999)
  /H3       (9)
  /H3D      (99)
  /H3M      (99)
  /H3Y      (9999)
  /H4       (9)
  /H4D      (99)
  /H4M      (99)
  /H4Y      (9999)
  /H5       (9)
  /H5D      (99)
  /H5M      (99)
  /H5Y      (9999)
  /H6       (9)
  /H6D      (99)
  /H6M      (99)
  /H6Y      (9999)
  /H7       (9)
  /H7D      (99)
  /H7M      (99)
  /H7Y      (9999)
  /H8       (9)
  /H8D      (99)
  /H8M      (99)
  /H8Y      (9999)
  /H9       (9)
  /H9D      (99)
  /H9M      (99)
  /H9Y      (9999)
  /H0       (9)
  /H0D      (99)
  /H0M      (99)
  /H0Y      (9999)
  /H10      (9)
  /H11      (9)
  /H11B     (9)
  /H12A     (9)
  /H12B     (9)
  /H12C     (9)
  /H12D     (9)
  /H12E     (9)
  /H12F     (9)
  /H12G     (9)
  /H12H     (9)
  /H12I     (9)
  /H12J     (9)
  /H12K     (9)
  /H12L     (9)
  /H12M     (9)
  /H12N     (9)
  /H12O     (9)
  /H12P     (9)
  /H12Q     (9)
  /H12R     (9)
  /H12S     (9)
  /H12T     (9)
  /H12U     (9)
  /H12V     (9)
  /H12W     (9)
  /H12X     (9)
  /H12Y     (9)
  /H12Z     (9)
  /H13      (9)
  /H13B     (9)
  /H14      (9)
  /H15      (9)
  /H15A     (9)
  /H15B     (9)
  /H15C     (9)
  /H15D     (9)
  /H15E     (9)
  /H15F     (9)
  /H15G     (9)
  /H15H     (9)
  /H15I     (9)
  /H15J     (9)
  /H15K     (9)
  /H15L     (9)
  /H15M     (9)
  /H20      (9)
  /H21A     (9)
  /H21      (9)
  /H22      (9)
  /H31      (9)
  /H31B     (9)
  /H31C     (9)
  /H31D     (9)
  /H31E     (9)
  /H32A     (9)
  /H32B     (9)
  /H32C     (9)
  /H32D     (9)
  /H32E     (9)
  /H32F     (9)
  /H32G     (9)
  /H32H     (9)
  /H32I     (9)
  /H32J     (9)
  /H32K     (9)
  /H32L     (9)
  /H32M     (9)
  /H32N     (9)
  /H32O     (9)
  /H32P     (9)
  /H32Q     (9)
  /H32R     (9)
  /H32S     (9)
  /H32T     (9)
  /H32U     (9)
  /H32V     (9)
  /H32W     (9)
  /H32X     (9)
  /H32Y     (9)
  /H32Z     (9)
  /H33      (9)
  /H33D     (99)
  /H33M     (99)
  /H33Y     (9999)
  /H34      (9)
  /H35      (9)
  /H36A     (9)
  /H36B     (9)
  /H36C     (9)
  /H36D     (9)
  /H36E     (9)
  /H36F     (9)
  /H37A     (9)
  /H37B     (9)
  /H37C     (9)
  /H37D     (9)
  /H37E     (9)
  /H37F     (9)
  /H37G     (9)
  /H37H     (9)
  /H37I     (9)
  /H37J     (9)
  /H37K     (9)
  /H37L     (9)
  /H37M     (9)
  /H37N     (9)
  /H37O     (9)
  /H37P     (9)
  /H37X     (9)
  /H37Y     (9)
  /H37Z     (9)
  /H38      (9)
  /H39      (9)
  /H40      (9)
  /H40D     (99)
  /H40M     (99)
  /H40Y     (9999)
  /H41A     (9)
  /H41B     (9)
  /H42      (9)
  /H43      (9)
  /H44A     (99)
  /H44B     (99)
  /H44C     (9)
  /H45      (99)
  /H46A     (99)
  /H46B     (99)
  /H47      (9)
  /HW2      (9999)
  /HW3      (9999)
  /HW4      (9999)
  /HW5      (9999)
  /HW6      (99999)
  /HW7      (9999)
  /HW8      (9999)
  /HW9      (99999)
  /HW10     (9999)
  /HW11     (9999)
  /HW12     (99999)
  /HW13     (9)
  /HW15     (9)
  /HW16     (99)
  /HW51     (99)
  /HW52     (9)
  /HW53     (999)
  /HW55     (9)
  /HW56     (9999)
  /HW57     (9)
  /HW58     (9)
  /HW70     (9999)
  /HW71     (9999)
  /HW72     (9999)
  /HW73     (9999)
  /ML0      (9)
  /ML1      (99)
  /ML2      (9)
  /ML11     (9)
  /ML12     (9)
  /ML13A    (9)
  /ML13B    (9)
  /ML13C    (9)
  /ML13D    (9)
  /ML13E    (9)
  /ML13F    (9)
  /ML13G    (9)
  /ML13H    (9)
  /ML13I    (9)
  /ML13J    (9)
  /ML13K    (9)
  /ML13L    (9)
  /ML13M    (9)
  /ML13N    (9)
  /ML13O    (9)
  /ML13P    (9)
  /ML13X    (9)
  /ML13Y    (9)
  /ML13Z    (9)
  /ML14A    (9)
  /ML14B    (9)
  /ML14Y    (9)
  /ML14Z    (9)
  /ML15A    (9)
  /ML15B    (9)
  /ML15C    (9)
  /ML16A    (9)
  /ML16B    (9)
  /ML16C    (9)
  /ML17A    (9)
  /ML17B    (9)
  /ML17C    (9)
  /ML18A    (9)
  /ML18B    (9)
  /ML18C    (9)
  /ML19A    (9)
  /ML19B    (9)
  /ML19C    (9)
  /ML19D    (9)
  /ML19E    (9)
  /ML19F    (9)
  /ML19X    (9)
  /ML19Y    (9)
  /ML19Z    (9)
  /ML20A    (9)
  /ML20B    (9)
  /ML20C    (9)
  /ML21A    (9)
  /ML21B    (9)
  /ML21C    (9)
  /ML22A    (9)
  /ML22B    (9)
  /ML22C    (9)
  /ML23A    (9)
  /ML23B    (9)
  /ML23C    (9)
  /ML24C    (9)
  /SLANG    (9)
  /S106     (99)
  /S115     (999)
  /S205CA   (9)
  /S205CB   (9)
  /S205CC   (9)
  /S205CD   (9)
  /S205CE   (9)
  /S205CX   (9)
  /S205CZ   (9)
  /S566     (99)
  /S567A    (9)
  /S567B    (9)
  /S567C    (9)
  /S568A    (9)
  /S568B    (9)
  /S572     (9)
  /S573     (99)
  /S574AA   (9)
  /S574AB   (9)
  /S574AX   (9)
  /S574AY   (9)
  /S574BA   (9)
  /S574BB   (9)
  /S574BX   (9)
  /S574BY   (9)
  /S574CA   (9)
  /S574CB   (9)
  /S574CX   (9)
  /S574CY   (9)
  /S574DA   (9)
  /S574DB   (9)
  /S574DX   (9)
  /S574DY   (9)
  /S574EA   (9)
  /S574EB   (9)
  /S574EX   (9)
  /S574EY   (9)
  /S574FA   (9)
  /S574FB   (9)
  /S574FX   (9)
  /S574FY   (9)
  /S575     (9)
  /S576     (9)
  /S577     (9)
  /S578     (9)
  /S579     (9)
  /S580     (9)
  /S581     (9)
  /S582     (9)
  /S583     (9)
  /S584     (9)
  /S623A    (99)
  /S623B    (99)
  /S623C    (99)
  /S626A    (99)
  /S714D    (9)
  /S826E    (9)
  /S827A    (9)
  /S827B    (9)
  /S827C    (9)
  /S907A    (9)
  /S910B    (9)
  /S910D    (9)
  /S910E    (9)
  /S1011A   (9)
  /S1011B   (9)
  /S1011C   (9)
  /S1011D   (9)
  /S1011E   (9)
  /S1011F   (9)
  /S1013    (9)
  /S1014A   (9)
  /S1014B   (9)
  /S1014C   (9)
  /S1014D   (9)
  /S1014E   (9)
  /S1014F   (9)
  /S1014I   (9)
  /S1014J   (9)
  /S1014K   (9)
  /S1014M   (9)
  /S1014N   (9)
  /S1014O   (9)
  /S1014P   (9)
  /S1014S   (9)
  /S1014T   (9)
  /S1014V   (9)
  /S1014X   (9)
  /SDV18    (9)
  /SDV24    (9)
  /S412B    (99)
  /S412D    (99)
  /S412F    (99)
  /S425AA   (9)
  /S425AB   (9)
  /S425AC   (9)
  /S425AD   (9)
  /S425AE   (9)
  /S425AF   (9)
  /S425AI   (9)
  /S425AJ   (9)
  /S425AK   (9)
  /S425AM   (9)
  /S425AN   (9)
  /S425AP   (9)
  /S425AS   (9)
  /S425AT   (9)
  /S425AU   (9)
  /S425AV   (9)
  /S425AX   (9)
  /S435A    (9)
  /S452N    (99)
  /S460B    (99)
  /S506N1   (9)
  /S506N1D  (99)
  /S506N1M  (99)
  /S506N1Y  (9999)
  /S506N2   (9)
  /S506N2D  (99)
  /S506N2M  (99)
  /S506N2Y  (9999)
  /S506N3   (9)
  /S506N3D  (99)
  /S506N3M  (99)
  /S506N3Y  (9999)
  /S506R1   (9)
  /S506R1D  (99)
  /S506R1M  (99)
  /S506R1Y  (9999)
  /S506R2   (9)
  /S506R2D  (99)
  /S506R2M  (99)
  /S506R2Y  (9999)
  /S506R3   (9)
  /S506R3D  (99)
  /S506R3M  (99)
  /S506R3Y  (9999)
  /S506MR   (9)
  /S506MRD  (99)
  /S506MRM  (99)
  /S506MRY  (9999)
  /S517B    (9)
  /S561A    (9)
  /S561BA   (9)
  /S561BB   (9)
  /S561BC   (9)
  /S561BD   (9)
  /S561BX   (9)
 .
VALUE LABELS
   V013    
      1 "15-19"
      2 "20-24"
      3 "25-29"
      4 "30-34"
      5 "35-39"
      6 "40-44"
      7 "45-49"
  /V014    
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /V015    
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partially completed"
      6 "Respondent incapacitated"
      7 "Other"
  /V018    
      0 "No calendar"
  /V019    
      0 "No calendar"
  /V019A   
      0 "No calendar"
  /V020    
      0 "All woman sample"
      1 "Ever married sample"
  /V022    
      1 "Nyarugenge - urban"
      2 "Nyarugenge - rural"
      3 "Gasabo - urban"
      4 "Gasabo - rural"
      5 "Kicukiro - urban"
      6 "Kicukiro - rural"
      7 "Nyanza - urban"
      8 "Nyanza - rural"
      9 "Gisagara - urban"
     10 "Gisagara - rural"
     11 "Nyaruguru - urban"
     12 "Nyaruguru - rural"
     13 "Huye - urban"
     14 "Huye - rural"
     15 "Nyamagabe - urban"
     16 "Nyamagabe - rural"
     17 "Ruhango - urban"
     18 "Ruhango - rural"
     19 "Muhanga - urban"
     20 "Muhanga - rural"
     21 "Kamonyi - urban"
     22 "Kamonyi - rural"
     23 "Karongi - urban"
     24 "Karongi - rural"
     25 "Rutsiro - urban"
     26 "Rutsiro - rural"
     27 "Rubavu - urban"
     28 "Rubavu - rural"
     29 "Nyabihu - urban"
     30 "Nyabihu - rural"
     31 "Ngororero - urban"
     32 "Ngororero - rural"
     33 "Rusizi - urban"
     34 "Rusizi - rural"
     35 "Nyamasheke - urban"
     36 "Nyamasheke - rural"
     37 "Rulindo - urban"
     38 "Rulindo - rural"
     39 "Gakenke - urban"
     40 "Gakenke - rural"
     41 "Musanze - urban"
     42 "Musanze - rural"
     43 "Burera - urban"
     44 "Burera - rural"
     45 "Gicumbi - urban"
     46 "Gicumbi - rural"
     47 "Rwamagana - urban"
     48 "Rwamagana - rural"
     49 "Nyagatare - urban"
     50 "Nyagatare - rural"
     51 "Gatsibo - urban"
     52 "Gatsibo - rural"
     53 "Kayonza - urban"
     54 "Kayonza - rural"
     55 "Kirehe - urban"
     56 "Kirehe - rural"
     57 "Ngoma - urban"
     58 "Ngoma - rural"
     59 "Bugesera - urban"
     60 "Bugesera - rural"
  /V023    
      1 "Nyarugenge - urban"
      2 "Nyarugenge - rural"
      3 "Gasabo - urban"
      4 "Gasabo - rural"
      5 "Kicukiro - urban"
      6 "Kicukiro - rural"
      7 "Nyanza - urban"
      8 "Nyanza - rural"
      9 "Gisagara - urban"
     10 "Gisagara - rural"
     11 "Nyaruguru - urban"
     12 "Nyaruguru - rural"
     13 "Huye - urban"
     14 "Huye - rural"
     15 "Nyamagabe - urban"
     16 "Nyamagabe - rural"
     17 "Ruhango - urban"
     18 "Ruhango - rural"
     19 "Muhanga - urban"
     20 "Muhanga - rural"
     21 "Kamonyi - urban"
     22 "Kamonyi - rural"
     23 "Karongi - urban"
     24 "Karongi - rural"
     25 "Rutsiro - urban"
     26 "Rutsiro - rural"
     27 "Rubavu - urban"
     28 "Rubavu - rural"
     29 "Nyabihu - urban"
     30 "Nyabihu - rural"
     31 "Ngororero - urban"
     32 "Ngororero - rural"
     33 "Rusizi - urban"
     34 "Rusizi - rural"
     35 "Nyamasheke - urban"
     36 "Nyamasheke - rural"
     37 "Rulindo - urban"
     38 "Rulindo - rural"
     39 "Gakenke - urban"
     40 "Gakenke - rural"
     41 "Musanze - urban"
     42 "Musanze - rural"
     43 "Burera - urban"
     44 "Burera - rural"
     45 "Gicumbi - urban"
     46 "Gicumbi - rural"
     47 "Rwamagana - urban"
     48 "Rwamagana - rural"
     49 "Nyagatare - urban"
     50 "Nyagatare - rural"
     51 "Gatsibo - urban"
     52 "Gatsibo - rural"
     53 "Kayonza - urban"
     54 "Kayonza - rural"
     55 "Kirehe - urban"
     56 "Kirehe - rural"
     57 "Ngoma - urban"
     58 "Ngoma - rural"
     59 "Bugesera - urban"
     60 "Bugesera - rural"
  /V024    
      1 "Kigali City"
      2 "South"
      3 "West"
      4 "North"
      5 "East"
  /V025    
      1 "Urban"
      2 "Rural"
  /V026    
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
  /V034    
      0 "Husband not in household"
  /V042    
      0 "Not selected"
      1 "Selected"
  /V044    
      0 "Woman not selected"
      1 "Woman selected and interviewed"
      2 "Woman selected, but privacy not possible"
      3 "Woman selected, but not interviewed"
  /V101    
      1 "Kigali City"
      2 "South"
      3 "West"
      4 "North"
      5 "East"
  /V102    
      1 "Urban"
      2 "Rural"
  /V103    
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
  /V104    
     95 "Always"
     96 "Visitor"
     97 "Inconsistent"
     98 "Don't know"
  /V105    
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
  /V106    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
  /V107    
      0 "No years completed at level V106"
  /V113    
     10 "PIPED WATER"
     11 "Piped into dwelling"
     12 "Piped to yard/plot"
     13 "Public tap/standpipe"
     20 "TUBE WELL WATER"
     21 "Tube well or borehole"
     30 "DUG WELL (OPEN/PROTECTED)"
     31 "Protected well"
     32 "Unprotected well"
     40 "SURFACE WATER"
     41 "Protected spring"
     42 "Unprotected spring"
     43 "River/dam/lake/ponds/stream/canal/irrigation channel"
     51 "Rainwater"
     61 "Tanker truck"
     62 "Cart with small tank"
     71 "Bottled water"
     96 "Other"
     97 "Not a de jure resident"
  /V115    
    996 "On premises"
    997 "Not a de jure resident"
    998 "Don't know"
  /V116    
     10 "FLUSH TOILET"
     11 "Flush to piped sewer system"
     12 "Flush to septic tank"
     13 "Flush to pit latrine"
     14 "Flush to somewhere else"
     15 "Flush, don't know where"
     20 "PIT TOILET LATRINE"
     21 "Ventilated Improved Pit latrine (VIP)"
     22 "Pit latrine with slab"
     23 "Pit latrine without slab/open pit"
     30 "NO FACILITY"
     31 "No facility/bush/field"
     41 "Composting toilet"
     42 "Bucket toilet"
     43 "Hanging toilet/latrine"
     96 "Other"
     97 "Not a de jure resident"
  /V119    
      0 "No"
      1 "Yes"
      7 "Not a de jure resident"
  /V120    
      0 "No"
      1 "Yes"
      7 "Not a de jure resident"
  /V121    
      0 "No"
      1 "Yes"
      7 "Not a de jure resident"
  /V122    
      0 "No"
      1 "Yes"
      7 "Not a de jure resident"
  /V123    
      0 "No"
      1 "Yes"
      7 "Not a de jure resident"
  /V124    
      0 "No"
      1 "Yes"
      7 "Not a de jure resident"
  /V125    
      0 "No"
      1 "Yes"
      7 "Not a de jure resident"
  /V127    
     11 "Earth, sand"
     12 "Dung"
     21 "Wood planks"
     22 "Palm, bamboo"
     31 "Parquet, polished wood"
     32 "Vinyl, asphalt strips"
     33 "Ceramic tiles"
     34 "Cement"
     35 "Carpet"
     96 "Other"
     97 "Not a de jure resident"
  /V128    
     11 "No walls"
     12 "Cane / palm / trunks"
     13 "Dirt"
     21 "Bamboo with mud"
     22 "Stone with mud"
     23 "Uncovered adobe"
     24 "Plywood"
     25 "Cardboard"
     26 "Reused wood"
     27 "Trunks with mud"
     31 "Cement"
     32 "Stone with lime / cement"
     33 "Bricks"
     34 "Cement blocks"
     35 "Covered adobe"
     36 "Wood planks / shingles"
     96 "Other"
     97 "Not a de jure resident"
  /V129    
     11 "No roof"
     12 "Thatch / palm leaf"
     13 "Sod"
     21 "Rustic mat/plastic"
     22 "Palm / bamboo"
     23 "Wood planks"
     24 "Cardboard"
     31 "Metal"
     32 "Wood"
     33 "Calamine / cement fiber"
     34 "Ceramic tiles"
     35 "Cement"
     36 "Roofing shingles"
     96 "Other"
     97 "Not a de jure resident"
  /V130    
      1 "Catholic"
      2 "Protestant"
      3 "Adventist"
      4 "Muslim"
      5 "Jehovah Witness"
      6 "Traditional"
      7 "No religion"
     96 "Other"
  /V133    
     97 "Inconsistent"
  /V134    
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
  /V135    
      1 "Usual resident"
      2 "Visitor"
  /V139    
      0 "Abroad"
      1 "Kigali City"
      2 "South"
      3 "West"
      4 "North"
      5 "East"
     97 "Not de jure resident"
  /V140    
      0 "Abroad"
      1 "Urban"
      2 "Rural"
      7 "Not a de jure resident"
  /V141    
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
      7 "Not a de jure resident"
  /V149    
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
  /V150    
      1 "Head"
      2 "Wife"
      3 "Daughter"
      4 "Daughter-in-law"
      5 "Granddaughter"
      6 "Mother"
      7 "Mother-in-law"
      8 "Sister"
      9 "Co-spouse"
     10 "Other relative"
     11 "Adopted/foster child"
     12 "Not related"
     98 "Don't know"
  /V151    
      1 "Male"
      2 "Female"
  /V152    
     97 "97+"
     98 "Don't know"
  /V153    
      0 "No"
      1 "Yes"
      7 "Not a de jure resident"
  /V155    
      0 "Cannot read at all"
      1 "Able to read only parts of sentence"
      2 "Able to read whole sentence"
      3 "No card with required language"
      4 "Blind/visually impaired"
  /V156    
      0 "No"
      1 "Yes"
  /V157    
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /V158    
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /V159    
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
  /V160    
      0 "No"
      1 "Yes"
      7 "Not a de jure resident"
  /V161    
      1 "Electricity"
      2 "LPG"
      3 "Natural gas"
      4 "Biogas"
      5 "Kerosene"
      6 "Coal, lignite"
      7 "Charcoal"
      8 "Wood"
      9 "Straw/shrubs/grass"
     10 "Agricultural crop"
     11 "Animal dung"
     95 "No food cooked in house"
     96 "Other"
     97 "Not a de jure resident"
  /V166    
      0 "0 ppm (no iodine)"
      7 "7 ppm"
     15 "15 ppm"
     30 "30 ppm"
    994 "Salt not tested"
    995 "No salt"
    997 "Not a de jure resident"
  /V167    
      0 "None"
     90 "90+"
  /V168    
      0 "No"
      1 "Yes"
  /V190    
      1 "Poorest"
      2 "Poorer"
      3 "Middle"
      4 "Richer"
      5 "Richest"
  /ML101   
      0 "No net"
      1 "Only treated nets"
      2 "Both treated and untreated nets"
      3 "Only untreated nets"
  /V208    
      0 "No births"
  /V209    
      0 "No births"
  /V213    
      0 "No or unsure"
      1 "Yes"
  /V215    
    100 "Day of interview"
    101 "Days: 1"
    199 "Days: number missing"
    201 "Weeks: 1"
    299 "Weeks: number missing"
    301 "Months: 1"
    399 "Months: number missing"
    401 "Years: 1"
    499 "Years: number missing"
    994 "In menopause/had hysterectomy"
    995 "Before last birth"
    996 "Never menstruated"
    997 "Inconsistent"
    998 "Don't know"
  /V216    
      0 "No"
      1 "Yes"
  /V217    
      1 "During her period"
      2 "After period ended"
      3 "Middle of the cycle"
      4 "Before period begins"
      5 "At any time"
      6 "Other"
      8 "Don't know"
  /V220    
      6 "6+"
  /V221    
    996 "Negative interval"
  /V223    
      7 "Month - exact date"
      8 "None - date placed"
  /V225    
      1 "Then"
      2 "Later"
      3 "Not at all"
  /V226    
    994 "In menopause"
    995 "Before last birth"
    996 "Never menstruated"
    997 "Inconsistent"
    998 "Don't know"
  /V227    
      0 "No flag"
      1 "N > interval since birth"
      2 "N + amen. > interval"
      3 "N, but period not returned"
      4 "95, but no birth"
      5 "95, but period returned"
      6 "96, but period returned"
      7 "N, last period during pregnancy"
      8 "96, had children"
      9 "N, period before last birth"
  /V228    
      0 "No"
      1 "Yes"
  /V229    
     97 "Inconsistent"
     98 "Don't know"
  /V230    
   9997 "Inconsistent"
   9998 "Don't know"
  /V231    
   9997 "Inconsistent"
   9998 "Don't know"
  /V232    
      1 "Month and year"
      2 "From calendar"
      5 "Year"
      7 "Month"
      8 "None"
  /V233    
     97 "Inconsistent"
     98 "Don't know"
  /V234    
      0 "No"
      1 "Yes"
  /V235    
      0 "No prior child"
  /V237    
      0 "No"
      1 "Yes"
  /V239    
      0 "No"
      1 "Yes"
  /V240    
     97 "Inconsistent"
     98 "Don't know"
  /V241    
   9997 "Inconsistent"
   9998 "Don't know"
  /V242    
   9997 "Inconsistent"
   9998 "Don't know"
  /V243    
      1 "Month and year"
      2 "From calendar"
      5 "Year"
      7 "Month"
      8 "None"
  /V311    
      4 "4+"
      5 "Never used"
  /V312    
      0 "Not using"
      1 "Pill"
      2 "IUD"
      3 "Injections"
      4 "Diaphragm"
      5 "Condom"
      6 "Female sterilization"
      7 "Male sterilization"
      8 "Periodic abstinence"
      9 "Withdrawal"
     10 "Other"
     11 "Implants/Norplant"
     12 "Abstinence"
     13 "Lactational amenorrhea (LAM)"
     14 "Female condom"
     15 "Foam or jelly"
     16 "Emergency"
     17 "Other modern method"
     18 "Standard Days Method"
     19 "Specific method 2"
     20 "Specific method 3"
  /V313    
      0 "No method"
      1 "Folkloric method"
      2 "Traditional method"
      3 "Modern method"
  /V318    
      1 "Month and year - information complete"
      5 "Year - month imputed, age calculated"
      7 "Month - date placed"
      8 "None - date placed"
      9 "From calendar"
  /V319    
      1 "<2"
      2 "2-3"
      3 "4-5"
      4 "6-7"
      5 "8-9"
      6 "10+"
  /V320    
      1 "<25"
      2 "25-29"
      3 "30-34"
      4 "35-39"
      5 "40-44"
      6 "45-49"
  /V321    
      0 "Single, before marriage"
      1 "0-4"
      2 "5-9"
      3 "10-14"
      4 "15-19"
      5 "20-24"
      6 "25+"
  /V322    
      5 "5+"
  /V323    
      1 "Microgynon"
      2 "Lofemenal"
      3 "Ovrette"
     96 "Other"
     98 "Don't know"
  /V323A   
      1 "Prudence"
      2 "Pleasure plus"
      3 "Generic Condom"
     96 "Other"
     98 "Don't know"
  /V325A   
   9999995 "Free"
   9999998 "Don't know"
  /V326    
     10 "PUBLIC SECTOR"
     11 "Referral hospital"
     12 "Provincial/District hospital"
     13 "Health center"
     14 "Health post"
     15 "Outreach"
     16 "Community health worker"
     17 "Youth Center"
     19 "Other public health facility"
     20 "PRIVATE SECTOR"
     21 "Polyclinic"
     22 "Clinic"
     23 "Dispensary"
     24 "Pharmacy"
     25 "Family planning clinic"
     26 "Other private health facility"
     30 "OTHER SOURCE"
     31 "Kiosk/Shop/Bar"
     32 "Church"
     33 "Friend/Relative"
     96 "Other"
     98 "Don't know"
  /V327    
      1 "Government clinic/pharmacy"
      2 "Government home/community delivery"
      3 "NGO"
      4 "Private clinic/delivery"
      5 "Pharmacy"
      6 "Shop, church, friend"
      7 "Other"
      8 "Don't know"
  /V337    
     95 "All calendar {A core}"
     96 "96+ {B core}"
    997 "Inconsistent"
    998 "Don't know"
  /V359    
      1 "Pill"
      2 "IUD"
      3 "Injections"
      4 "Diaphragm"
      5 "Condom"
      6 "Female sterilization"
      7 "Male sterilization"
      8 "Periodic abstinence"
      9 "Withdrawal"
     10 "Other"
     11 "Norplant"
     12 "Abstinence"
     13 "Lactational amenorrhea"
     14 "Female condom"
     15 "Foam or jelly"
     16 "Emergency"
     17 "Other modern method"
     18 "Standard days method"
     19 "Specific method 3"
     20 "Specific method 4"
  /V360    
      1 "Became pregnant"
      2 "Wanted to become pregnant"
      3 "Husband disapproved"
      4 "Side effects"
      5 "Health concerns"
      6 "Access, availability"
      7 "Wanted more effective method"
      8 "Inconvenient to use"
      9 "Infrequent sex, husband away"
     10 "Cost"
     11 "Fatalistic"
     12 "Difficult pregnancy, menopause"
     13 "Marital dissolution"
     14 "Other"
     98 "Don't know"
  /V361    
      1 "Currently using"
      2 "Used since last birth"
      3 "Used before last birth"
      4 "Never used"
  /V362    
      1 "In next 12 months"
      2 "Use later"
      3 "Unsure about timing"
      4 "Unsure about use"
      5 "Does not intend"
      6 "Never had sex"
  /V363    
      1 "Pill"
      2 "IUD"
      3 "Injections"
      4 "Diaphragm"
      5 "Condom"
      6 "Female sterilization"
      7 "Male sterilization"
      8 "Periodic abstinence"
      9 "Withdrawal"
     10 "Other"
     11 "Norplant"
     12 "Abstinence"
     13 "Lactational amenorrhea"
     14 "Female condom"
     15 "Foam or jelly"
     17 "Specific method 1"
     18 "Specific method 2"
     19 "Specific method 3"
     20 "Specific method 4"
     98 "Don't know"
  /V364    
      1 "Using modern method"
      2 "Using traditional method"
      3 "Non-user - intends to use later"
      4 "Does not intend to use"
      5 "Never had sex"
  /V367    
      1 "Wanted then"
      2 "Wanted later"
      3 "Wanted no more"
  /V372    
      0 "Package not seen"
      1 "Package seen"
  /V372A   
      0 "Package not seen"
      1 "Package seen"
  /V375A   
     11 "Not married"
     20 "FERTILITY-RELATED"
     21 "Not having sex"
     22 "Infrequent sex"
     23 "Menopausal, hysterectomy"
     24 "Subfecund, infecund"
     25 "Postpartum, breastfeeding"
     26 "Wants more children"
     27 "Pregnant"
     30 "OPPOSITION TO USE"
     31 "Respondent opposed"
     32 "Husband opposed"
     33 "Others opposed"
     34 "Religious prohibition"
     40 "LACK OF KNOWLEDGE"
     41 "Knows no method"
     42 "Knows no source"
     50 "METHOD-RELATED"
     51 "Health concerns"
     52 "Fears side effects"
     53 "Lack of access"
     54 "Cost too much"
     55 "Inconvenient to use"
     56 "Interferes with body"
     96 "Other"
     98 "Don't know"
  /V376    
     11 "Not married"
     20 "FERTILITY-RELATED"
     22 "Infrequent sex"
     23 "Menopausal, hysterectomy"
     24 "Subfecund, infecund"
     26 "Wants more children"
     30 "OPPOSITION TO USE"
     31 "Respondent opposed"
     32 "Husband opposed"
     33 "Others opposed"
     34 "Religious prohibition"
     40 "LACK OF KNOWLEDGE"
     41 "Knows no method"
     42 "Knows no source"
     50 "METHOD-RELATED"
     51 "Health concerns"
     52 "Fears side effects"
     53 "Lack of access"
     54 "Cost too much"
     55 "Inconvenient to use"
     56 "Interferes with body"
     96 "Other"
     98 "Don't know"
  /V376A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V379    
     10 "PUBLIC SECTOR"
     20 "PRIVATE SECTOR"
     30 "OTHER SOURCE"
     96 "Other"
     98 "Don't know"
  /V380    
      1 "Government clinic/pharmacy"
      2 "Government home/community delivery"
      3 "NGO"
      4 "Private clinic/delivery"
      5 "Pharmacy"
      6 "Shop, church, friend"
      7 "Other"
      8 "Don't know"
  /V384A   
      0 "No"
      1 "Yes"
  /V384B   
      0 "No"
      1 "Yes"
  /V384C   
      0 "No"
      1 "Yes"
  /V393    
      0 "No"
      1 "Yes"
  /V394    
      0 "No"
      1 "Yes"
  /V395    
      0 "No"
      1 "Yes"
  /V3A00A  
      0 "No"
      1 "Yes"
  /V3A00B  
      0 "No"
      1 "Yes"
  /V3A00C  
      0 "No"
      1 "Yes"
  /V3A00D  
      0 "No"
      1 "Yes"
  /V3A00E  
      0 "No"
      1 "Yes"
  /V3A00F  
      0 "No"
      1 "Yes"
  /V3A00G  
      0 "No"
      1 "Yes"
  /V3A00H  
      0 "No"
      1 "Yes"
  /V3A00I  
      0 "No"
      1 "Yes"
  /V3A00J  
      0 "No"
      1 "Yes"
  /V3A00K  
      0 "No"
      1 "Yes"
  /V3A00L  
      0 "No"
      1 "Yes"
  /V3A00M  
      0 "No"
      1 "Yes"
  /V3A00N  
      0 "No"
      1 "Yes"
  /V3A00O  
      0 "No"
      1 "Yes"
  /V3A00P  
      0 "No"
      1 "Yes"
  /V3A00Q  
      0 "No"
      1 "Yes"
  /V3A00R  
      0 "No"
      1 "Yes"
  /V3A00S  
      0 "No"
      1 "Yes"
  /V3A00T  
      0 "No"
      1 "Yes"
  /V3A00U  
      0 "No"
      1 "Yes"
  /V3A00V  
      0 "No"
      1 "Yes"
  /V3A00W  
      0 "No"
      1 "Yes"
  /V3A00X  
      0 "No"
      1 "Yes"
  /V3A00Y  
      0 "No: knows a source"
      1 "Yes: knows no source"
  /V3A00Z  
      0 "No"
      1 "Yes"
  /V3A01   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V3A02   
      0 "No"
      1 "Yes"
  /V3A03   
      0 "No"
      1 "Yes"
  /V3A04   
      0 "No"
      1 "Yes"
  /V3A05   
      0 "No"
      1 "Yes"
  /V3A06   
      0 "No"
      1 "Yes"
  /V3A07   
     10 "PUBLIC SECTOR"
     11 "Referral hospital"
     12 "Provincial/District hospital"
     13 "Health center"
     14 "Health post"
     15 "Outreach"
     16 "Community health worker"
     17 "Youth facility"
     19 "Other public health facility"
     20 "PRIVATE SECTOR"
     21 "Polyclinic"
     22 "Clinic"
     23 "Dispensary"
     24 "Pharmacy"
     25 "Family planning clinic"
     26 "Other private"
     30 "OTHER SOURCE"
     31 "Kiosk/Shop/Bar"
     32 "Church"
     33 "Friend/Relative"
     96 "Other"
     98 "Don't know"
  /V3A08A  
      0 "No"
      1 "Yes"
  /V3A08B  
      0 "No"
      1 "Yes"
  /V3A08C  
      0 "No"
      1 "Yes"
  /V3A08D  
      0 "No"
      1 "Yes"
  /V3A08E  
      0 "No"
      1 "Yes"
  /V3A08F  
      0 "No"
      1 "Yes"
  /V3A08G  
      0 "No"
      1 "Yes"
  /V3A08H  
      0 "No"
      1 "Yes"
  /V3A08I  
      0 "No"
      1 "Yes"
  /V3A08J  
      0 "No"
      1 "Yes"
  /V3A08K  
      0 "No"
      1 "Yes"
  /V3A08L  
      0 "No"
      1 "Yes"
  /V3A08M  
      0 "No"
      1 "Yes"
  /V3A08N  
      0 "No"
      1 "Yes"
  /V3A08O  
      0 "No"
      1 "Yes"
  /V3A08P  
      0 "No"
      1 "Yes"
  /V3A08Q  
      0 "No"
      1 "Yes"
  /V3A08R  
      0 "No"
      1 "Yes"
  /V3A08S  
      0 "No"
      1 "Yes"
  /V3A08T  
      0 "No"
      1 "Yes"
  /V3A08U  
      0 "No"
      1 "Yes"
  /V3A08V  
      0 "No"
      1 "Yes"
  /V3A08W  
      0 "No"
      1 "Yes"
  /V3A08AA 
      0 "No"
      1 "Yes"
  /V3A08AB 
      0 "No"
      1 "Yes"
  /V3A08AC 
      0 "No"
      1 "Yes"
  /V3A08AD 
      0 "No"
      1 "Yes"
  /V3A08X  
      0 "No"
      1 "Yes"
  /V3A08Z  
      0 "No"
      1 "Yes: don't know"
  /V3A09A  
    998 "Don't know"
  /V3A09B  
    998 "Don't know"
  /V401    
      0 "No"
      1 "Yes"
  /V404    
      0 "No"
      1 "Yes"
  /V405    
      0 "No"
      1 "Yes"
  /V406    
      0 "No"
      1 "Yes"
  /V407    
     96 "On demand"
  /V408    
     96 "On demand"
  /V409    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V409A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V410    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V410A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V411    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V411A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V412    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V412A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V412B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V412C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V413    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V413A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V413B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V413C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V413D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414E   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414F   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414G   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414H   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414I   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414J   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414K   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414L   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414M   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414N   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414O   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414P   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414Q   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414R   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414S   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414T   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414U   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414V   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V414W   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V415    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V416    
      0 "Never heard of"
      1 "Used ORS"
      2 "Heard of ORS"
  /V426    
      0 "Immediately"
    100 "Within first hour"
    101 "Hours: 1"
    199 "Hours: number missing"
    201 "Days: 1"
    299 "Days: number missing"
  /V437    
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /V438    
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /V439    
   9998 "Flagged cases"
  /V440    
   9998 "Flagged cases"
  /V441    
   99998 "Flagged cases"
  /V442    
   99998 "Flagged cases"
  /V443    
   99998 "Flagged cases"
  /V444    
   99998 "Flagged cases"
  /V444A   
   9998 "Flagged cases"
  /V445    
   9998 "Flagged cases"
  /V446    
   9998 "Flagged cases"
  /V447    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
      7 "No measurement found in household"
  /V452A   
      1 "Under age 18"
      2 "Age 18 or older"
  /V452B   
      0 "Not in household"
  /V452C   
      1 "Granted"
      2 "Parent/other refused"
      3 "Respondent refused"
  /V453    
    994 "Not present"
    995 "Refused"
    996 "Other"
  /V454    
      0 "No/don't know"
      1 "Yes"
  /V455    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      6 "Other"
      7 "No measurement found in household"
  /V457    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
  /V458    
      0 "No"
      1 "Yes"
  /V459    
      0 "No"
      1 "Yes"
  /V460    
      0 "No"
      1 "All children"
      2 "Some children"
      3 "No net in household"
  /V461    
      0 "No"
      1 "Yes"
  /V462    
      0 "No"
      1 "Yes"
      2 "Never prepared meal"
  /V463A   
      0 "No"
      1 "Yes"
  /V463B   
      0 "No"
      1 "Yes"
  /V463C   
      0 "No"
      1 "Yes"
  /V463D   
      0 "No"
      1 "Yes"
  /V463E   
      0 "No"
      1 "Yes"
  /V463F   
      0 "No"
      1 "Yes"
  /V463G   
      0 "No"
      1 "Yes"
  /V463X   
      0 "No"
      1 "Yes"
  /V463Z   
      0 "No"
      1 "Yes, smokes nothing"
  /V464    
     80 "80+"
     98 "Don't know"
  /V465    
      1 "Used toilet/latrine"
      2 "Put/rinsed in toilet/latrine"
      3 "Put/rinsed into drain or ditch"
      4 "Throw into garbage"
      5 "Buried"
      6 "Rinse away"
      7 "Use disposable diapers"
      8 "Use washable diapers"
      9 "Left in the open/not disposed of"
     96 "Other"
  /V466    
      0 "No"
      1 "Yes"
      2 "Depends"
  /V467A   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467B   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467C   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467D   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467E   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467F   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467G   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467H   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467I   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467J   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467K   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467L   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V467M   
      0 "No problem"
      1 "Big problem"
      2 "Not a big problem"
  /V468    
      0 "See specific questions"
      1 "Last birth only"
      2 "All births in last 5 years"
  /V469E   
      0 "No"
      7 "7+"
      8 "DK"
  /V469F   
      0 "No"
      7 "7+"
      8 "DK"
  /V469X   
      0 "No"
      7 "7+"
      8 "DK"
  /V471A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V471B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V471C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V471D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V471E   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V471F   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V471G   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472E   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472F   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472G   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472H   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472I   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472J   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472K   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472L   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472M   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472N   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472O   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472P   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472Q   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472R   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472S   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472T   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V472U   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V473A   
      1 "Granted"
      2 "Parent/other responsible refused"
      3 "Respondent refused"
      4 "Sample not tested/lost/not enough DBS"
  /V473B   
      1 "Blood taken"
      2 "Not present"
      3 "Refused"
      4 "Sample not tested/lost/damaged/insufficient"
      5 "Not enough DBS to complete protocol"
      6 "Other"
  /V474    
      0 "No"
      1 "Yes"
  /V474A   
      0 "No"
      1 "Yes"
  /V474B   
      0 "No"
      1 "Yes"
  /V474C   
      0 "No"
      1 "Yes"
  /V474D   
      0 "No"
      1 "Yes"
  /V474E   
      0 "No"
      1 "Yes"
  /V474F   
      0 "No"
      1 "Yes"
  /V474G   
      0 "No"
      1 "Yes"
  /V474H   
      0 "No"
      1 "Yes"
  /V474I   
      0 "No"
      1 "Yes"
  /V474J   
      0 "No"
      1 "Yes"
  /V474K   
      0 "No"
      1 "Yes"
  /V474X   
      0 "No"
      1 "Yes"
  /V474Z   
      0 "No"
      1 "Yes"
  /V475    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V476    
      0 "No"
      1 "Yes, remain a secret"
      8 "Don't know/not sure/depends"
  /V477    
      0 "None"
     90 "90+"
     98 "Don't know"
  /V478    
      0 "None"
     90 "90+"
     98 "Don't know"
  /V479    
     10 "PUBLIC SECTOR"
     11 "Government hospital"
     12 "Government health center"
     16 "Other public sector"
     20 "PRIVATE SECTOR"
     21 "Private hospital/clinic/doctor"
     22 "Dental clinic/office"
     23 "Pharmacy"
     24 "Office or home of nurse/health worker"
     26 "Other private sector"
     30 "OTHER NON-MEDICAL"
     31 "Respondent's home"
     96 "Other"
  /V480    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V481    
      0 "No"
      1 "Yes"
  /V481A   
      0 "No"
      1 "Yes"
  /V481B   
      0 "No"
      1 "Yes"
  /V481C   
      0 "No"
      1 "Yes"
  /V481D   
      0 "No"
      1 "Yes"
  /V481E   
      0 "No"
      1 "Yes"
  /V481F   
      0 "No"
      1 "Yes"
  /V481G   
      0 "No"
      1 "Yes"
  /V481H   
      0 "No"
      1 "Yes"
  /V481X   
      0 "No"
      1 "Yes"
  /V482A   
      0 "No"
      1 "Yes"
      8 "Unsure"
  /V482B   
      0 "No"
      1 "Yes"
  /V482C   
      0 "No"
      1 "Yes"
      8 "Unsure"
  /V501    
      0 "Never in union"
      1 "Married"
      2 "Living with partner"
      3 "Widowed"
      4 "Divorced"
      5 "No longer living together/separated"
  /V502    
      0 "Never in union"
      1 "Currently in union/living with a man"
      2 "Formerly in union/living with a man"
  /V503    
      1 "Once"
      2 "More than once"
  /V504    
      1 "Living with her"
      2 "Staying elsewhere"
  /V505    
      0 "No other wives"
     98 "Don't know"
  /V506    
     98 "Don't know"
  /V510    
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /V513    
      0 "Never married"
      1 "0-4"
      2 "5-9"
      3 "10-14"
      4 "15-19"
      5 "20-24"
      6 "25-29"
      7 "30+"
  /V525    
      0 "Not had sex"
     96 "At first union"
     97 "Inconsistent"
     98 "Don't know"
  /V527    
    100 "<1 day ago"
    101 "Days: 1"
    199 "Days: number missing"
    201 "Weeks: 1"
    299 "Weeks: number missing"
    301 "Months: 1"
    399 "Months: number missing"
    401 "Years: 1"
    499 "Years: number missing"
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
  /V528    
     31 "31+ days"
     95 "Within last 4 weeks"
     96 "Before last birth"
     97 "Inconsistent"
     98 "Don't know"
  /V529    
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
  /V530    
      0 "No flag"
      1 "N > interval since birth"
      2 "N + abstinence > interval"
      3 "N, but sex not res."
      4 "96, but no birth"
      5 "96, but currently pregnant"
      6 "96, but resumed sex"
      7 "N, last sex before pregnancy"
      8 "N, inconsistent 4 weeks"
      9 "N, sex before last birth"
  /V531    
      0 "Not had sex"
     97 "Inconsistent"
     98 "Don't know"
  /V532    
      0 "No flag"
      1 "After interview"
      2 "After conception >= 1 year"
      3 "After conception < 1 year"
      4 "At marriage, but never married"
      5 "At marriage, but after conception"
      6 "After marriage"
  /V535    
      0 "No"
      1 "Formerly married"
      2 "Lived with a man"
  /V536    
      0 "Never had sex"
      1 "Active in last 4 weeks"
      2 "Not active in last 4 weeks - postpartum abstinence"
      3 "Not active in last 4 weeks - not postpartum abstinence"
  /V537    
     60 "60+"
     96 "Before last birth"
     97 "Inconsistent"
     98 "Don't know"
  /V538    
      1 "Death/widowhood"
      2 "Divorce"
      3 "Separation"
  /V539    
      1 "Respondent"
      2 "Other wife"
      3 "Spouse's children"
      4 "Spouse's family"
      6 "Other"
      7 "No property"
  /V540    
      0 "No"
      1 "Yes"
  /V541    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V602    
      1 "Have another"
      2 "Undecided"
      3 "No more"
      4 "Sterilized (respondent or partner)"
      5 "Declared infecund"
      6 "Never had sex"
  /V603    
    100 "Wanted now"
    101 "Months: 1"
    199 "Months: number missing"
    201 "Years: 1"
    299 "Years: number missing"
    993 "After marriage"
    994 "Soon, now"
    996 "Other, non-numeric"
    997 "Inconsistent"
    998 "Don't know"
  /V604    
      0 "<12 months"
      1 "1 year"
      2 "2 years"
      3 "3 years"
      4 "4 years"
      5 "5 years"
      6 "6+ years"
      7 "Non-numeric"
      8 "Don't know"
  /V605    
      1 "Wants within 2 years"
      2 "Wants after 2+ years"
      3 "Wants, unsure timing"
      4 "Undecided"
      5 "Wants no more"
      6 "Sterilized (respondent or partner)"
      7 "Declared infecund"
      8 "Never had sex"
  /V613    
     96 "Non-numeric response"
     98 "Don't know"
  /V614    
      6 "6+"
      7 "Non-numeric response"
  /V616    
    100 "Wanted now"
    101 "Months: 1"
    199 "Months: number missing"
    201 "Years: 1"
    299 "Years: number missing"
    993 "After marriage"
    994 "Soon/now"
    995 "Can't get pregnant"
    996 "Other"
    998 "Don't know"
  /V621    
      1 "Both want same"
      2 "Husband wants more"
      3 "Husband wants fewer"
      8 "Don't know"
  /V623    
      0 "Fecund"
      1 "Pregnant"
      2 "Postpartum amenorrheic"
      3 "Infecund, menopausal"
  /V624    
      0 "Never had sex"
      1 "Unmet need for spacing"
      2 "Unmet need for limiting"
      3 "Using for spacing"
      4 "Using for limiting"
      5 "Spacing failure"
      6 "Limiting failure"
      7 "No unmet need"
      8 "Not married and no sex in last 30 days"
      9 "Infecund, menopausal"
  /V625    
      0 "Fecund"
      1 "Pregnant"
      2 "Postpartum amenorrheic"
      3 "Infecund, menopausal"
  /V626    
      0 "Never had sex"
      1 "Unmet need for spacing"
      2 "Unmet need for limiting"
      3 "Using for spacing"
      4 "Using for limiting"
      5 "Spacing failure"
      6 "Limiting failure"
      7 "No unmet need"
      8 "Not married and no sex in last 30 days"
      9 "Infecund, menopausal"
  /V625A   
      0 "Fecund"
      1 "Pregnant"
      2 "Postpartum amenorrheic"
      3 "Infecund, menopausal"
  /V626A   
      0 "Never had sex"
      1 "Unmet need for spacing"
      2 "Unmet need for limiting"
      3 "Using for spacing"
      4 "Using for limiting"
      7 "No unmet need"
      8 "Not married and no sex in last 30 days"
      9 "Infecund, menopausal"
  /V627    
     96 "Other"
     98 "Don't know"
  /V628    
     96 "Other"
     98 "Don't know"
  /V629    
     96 "Other"
     98 "Don't know"
  /V631    
      1 "Big problem"
      2 "Small problem"
      3 "No problem"
      4 "Says she can't get pregnant/not having sex"
  /V632    
      1 "Mainly respondent"
      2 "Mainly husband, partner"
      3 "Joint decision"
      6 "Other"
  /V633A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V633B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V633C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V633D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V633E   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V633F   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V633G   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V634    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V701    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
  /V702    
      0 "No years completed at level V702"
     98 "Don't know"
  /V704    
      0 "Not working/did not work"
      1 "Commissioned armed forces officers"
      2 "Non-commissioned armed forces officers"
      3 "Armed forces occupations, other ranks"
     11 "Chief executives, senior officials and legislators"
     12 "Administrative and commercial managers"
     13 "Production and specialized services managers"
     14 "Hospitality, retail and other services managers"
     21 "Science and engineering professionals"
     22 "Health professionals"
     23 "Teaching professionals"
     24 "Business and administration professionals"
     25 "Information and communications technology professionals"
     26 "Legal, social and cultural professionals"
     31 "Science and engineering associate professionals"
     32 "Health associate professionals"
     33 "Business and administration associate professionals"
     34 "Legal, social, cultural and related associate professionals"
     35 "Information and communications technicians"
     41 "General and keyboard clerks"
     42 "Customer services clerks"
     43 "Numerical and material recording clerks"
     44 "Other clerical support workers"
     51 "Personal service workers"
     52 "Sales workers"
     53 "Personal care workers"
     54 "Protective services workers"
     61 "Market-oriented skilled agricultural workers"
     62 "Market-oriented skilled forestry, fishery and hunting workers"
     63 "Subsistence farmers, fishers, hunters and gatherers"
     71 "Building and related trades workers, excluding electricians"
     72 "Metal, machinery and related trades workers"
     73 "Handicraft and printing workers"
     74 "Electrical and electronic trades workers"
     75 "Food processing, wood working, garment and other craft and related trades workers"
     81 "Stationary plant and machine operators"
     82 "Assemblers"
     83 "Drivers and mobile plant operators"
     91 "Cleaners and helpers"
     92 "Agricultural, forestry and fishery laborers"
     93 "Laborers in mining, construction, manufacturing and transport"
     94 "Food preparation assistants"
     95 "Street and related sales and service workers"
     96 "Refuse workers and other elementary workers"
  /V705    
      0 "Did not work"
      1 "Professional/technical/managerial"
      2 "Clerical"
      3 "Sales"
      4 "Agricultural - self employed"
      5 "Agricultural - employee"
      6 "Household and domestic"
      7 "Services"
      8 "Skilled manual"
      9 "Unskilled manual"
     98 "Don't know"
  /V714    
      0 "No"
      1 "Yes"
  /V714A   
      0 "No"
      1 "Yes"
  /V715    
     97 "Inconsistent"
     98 "Don't know"
  /V716    
      0 "Not working"
      1 "Commissioned armed forces officers"
      2 "Non-commissioned armed forces officers"
      3 "Armed forces occupations, other ranks"
     11 "Chief executives, senior officials and legislators"
     12 "Administrative and commercial managers"
     13 "Production and specialised services managers"
     14 "Hospitality, retail and other services managers"
     21 "Science and engineering professionals"
     22 "Health professionals"
     23 "Teaching professionals"
     24 "Business and administration professionals"
     25 "Information and communications technology professionals"
     26 "Legal, social and cultural professionals"
     31 "Science and engineering associate professionals"
     32 "Health associate professionals"
     33 "Business and administration associate professionals"
     34 "Legal, social, cultural and related associate professionals"
     35 "Information and communications technicians"
     41 "General and keyboard clerks"
     42 "Customer services clerks"
     43 "Numerical and material recording clerks"
     44 "Other clerical support workers"
     51 "Personal service workers"
     52 "Sales workers"
     53 "Personal care workers"
     54 "Protective services workers"
     61 "Market-oriented skilled agricultural workers"
     62 "Market-oriented skilled forestry, fishery and hunting workers"
     63 "Subsistence farmers, fishers, hunters and gatherers"
     71 "Building and related trades workers, excluding electricians"
     72 "Metal, machinery and related trades workers"
     73 "Handicraft and printing workers"
     74 "Electrical and electronic trades workers"
     75 "Food processing, wood working, garment and other craft and related trades workers"
     81 "Stationary plant and machine operators"
     82 "Assemblers"
     83 "Drivers and mobile plant operators"
     91 "Cleaners and helpers"
     92 "Agricultural, forestry and fishery laborers"
     93 "Laborers in mining, construction, manufacturing and transport"
     94 "Food preparation assistants"
     95 "Street and related sales and service workers"
     96 "Refuse workers and other elementary workers"
  /V717    
      0 "Not working"
      1 "Professional/technical/managerial"
      2 "Clerical"
      3 "Sales"
      4 "Agricultural - self employed"
      5 "Agricultural - employee"
      6 "Household and domestic"
      7 "Services"
      8 "Skilled manual"
      9 "Unskilled manual"
     98 "Don't know"
  /V719    
      1 "For family member"
      2 "For someone else"
      3 "Self-employed"
  /V721    
      1 "At home"
      2 "Away"
  /V729    
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
      8 "Don't know"
  /V730    
     96 "96+"
     98 "Don't know"
  /V731    
      0 "No"
      1 "In the past year"
      2 "Currently working"
      3 "Have a job, but on leave last 7 days"
  /V732    
      1 "All year"
      2 "Seasonal"
      3 "Occasional"
  /V739    
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
  /V740    
      0 "Own land"
      1 "Family land"
      2 "Someone else's land"
      3 "Rented land"
      8 "Don't know"
  /V741    
      0 "Not paid"
      1 "Cash only"
      2 "Cash and in-kind"
      3 "In-kind only"
  /V743A   
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
      6 "Other"
  /V743B   
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
      6 "Other"
  /V743C   
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
      6 "Other"
  /V743D   
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
      6 "Other"
  /V743E   
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
      6 "Other"
  /V743F   
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
      6 "Other"
      7 "Husband/partner has no earnings"
  /V744A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V744B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V744C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V744D   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V744E   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /V745A   
      0 "Does not own"
      1 "Alone only"
      2 "Jointly only"
      3 "Both alone and jointly"
  /V745B   
      0 "Does not own"
      1 "Alone only"
      2 "Jointly only"
      3 "Both alone and jointly"
  /V746    
      1 "More than him"
      2 "Less than him"
      3 "About the same"
      4 "Husband/partner doesn't bring in money"
      8 "Don't know"
  /B0      
      0 "Single birth"
      1 "1st of multiple"
      2 "2nd of multiple"
      3 "3rd of multiple"
      4 "4th of multiple"
      5 "5th of multiple"
  /B4      
      1 "Male"
      2 "Female"
  /B5      
      0 "No"
      1 "Yes"
  /B6      
    100 "Died on day of birth"
    101 "Days: 1"
    199 "Days: number missing"
    201 "Months: 1"
    299 "Months: number missing"
    301 "Years: 1"
    399 "Years: number missing"
    997 "Inconsistent"
    998 "Don't know"
  /B9      
      0 "Respondent"
      1 "Father"
      2 "Other relative"
      3 "Someone else"
      4 "Lives elsewhere"
  /B10     
      1 "Month and year - information complete"
      2 "Month and age - year imputed"
      3 "Year and age - month imputed"
      4 "Year and age - year ignored"
      5 "Year - age/month imputed"
      6 "Age - year/month imputed"
      7 "Month - age/year imputed"
      8 "None - all imputed"
  /B13     
      0 "No flag"
      1 "> interview"
      2 "< breastfeeding"
      3 "< age supplemented"
      4 "< first breastfed"
      5 "< last vaccination"
      6 "Outside range"
      7 "Imputed, units given"
      8 "Imputed, no units"
  /B15     
      0 "No"
      1 "Yes"
  /B16     
      0 "Not listed in household"
  /M1      
      0 "Received no injection"
      7 "7+"
      8 "Don't know"
  /M1A     
      0 "Received no injection"
      7 "7+"
      8 "Don't know"
  /M1B     
     97 "Inconsistent"
     98 "Don't know month"
  /M1C     
   9997 "Inconsistent"
   9998 "Don't know year"
  /M1E     
   9996 "Can't be determined"
  /M2A     
      0 "No"
      1 "Yes"
  /M2B     
      0 "No"
      1 "Yes"
  /M2C     
      0 "No"
      1 "Yes"
  /M2D     
      0 "No"
      1 "Yes"
  /M2E     
      0 "No"
      1 "Yes"
  /M2F     
      0 "No"
      1 "Yes"
  /M2G     
      0 "No"
      1 "Yes"
  /M2H     
      0 "No"
      1 "Yes"
  /M2I     
      0 "No"
      1 "Yes"
  /M2J     
      0 "No"
      1 "Yes"
  /M2K     
      0 "No"
      1 "Yes"
  /M2L     
      0 "No"
      1 "Yes"
  /M2M     
      0 "No"
      1 "Yes"
  /M2N     
      0 "No: some care"
      1 "Yes: no care"
  /M3A     
      0 "No"
      1 "Yes"
  /M3B     
      0 "No"
      1 "Yes"
  /M3C     
      0 "No"
      1 "Yes"
  /M3D     
      0 "No"
      1 "Yes"
  /M3E     
      0 "No"
      1 "Yes"
  /M3F     
      0 "No"
      1 "Yes"
  /M3G     
      0 "No"
      1 "Yes"
  /M3H     
      0 "No"
      1 "Yes"
  /M3I     
      0 "No"
      1 "Yes"
  /M3J     
      0 "No"
      1 "Yes"
  /M3K     
      0 "No"
      1 "Yes"
  /M3L     
      0 "No"
      1 "Yes"
  /M3M     
      0 "No"
      1 "Yes"
  /M3N     
      0 "No: some assistance"
      1 "Yes: no assistance"
  /M4      
     93 "Ever breastfed, not currently breastfeeding"
     94 "Never breastfed"
     95 "Still breastfeeding"
     96 "Breastfed until died"
     97 "Inconsistent"
     98 "Don't know"
  /M5      
     93 "Ever breastfed, not currently breastfeeding"
     94 "Never breastfed"
     97 "Inconsistent"
     98 "Don't know"
  /M6      
     96 "Period not returned"
     97 "Inconsistent"
     98 "Don't know"
  /M7      
     97 "Inconsistent"
     98 "Don't know"
  /M8      
     96 "Still abstaining"
     97 "Inconsistent"
     98 "Don't know"
  /M9      
     97 "Inconsistent"
     98 "Don't know"
  /M10     
      1 "Then"
      2 "Later"
      3 "No more"
  /M11     
    101 "Months: 1"
    199 "Months: number missing"
    201 "Years: 1"
    299 "Years: number missing"
    998 "Don't know"
  /M13     
     98 "Don't know"
  /M14     
      0 "No antenatal visits"
     98 "Don't know"
  /M15     
     10 "HOME"
     11 "Respondent's home"
     12 "Other home"
     20 "PUBLIC SECTOR"
     21 "Government hospital"
     22 "Provincial/District hospital"
     23 "Health center"
     24 "Health post"
     26 "Other public sector"
     30 "PRIVATE SECTOR"
     31 "Private hospital/clinic"
     32 "Polyclinic"
     33 "Dispensary"
     36 "Other private sector"
     37 "On way to health facility"
     96 "Other"
  /M17     
      0 "No"
      1 "Yes"
  /M18     
      1 "Very large"
      2 "Larger than average"
      3 "Average"
      4 "Smaller than average"
      5 "Very small"
      8 "Don't know"
  /M19     
   9996 "Not weighed at birth"
   9998 "Don't know"
  /M19A    
      0 "Not weighed"
      1 "From written card"
      2 "From mother's recall"
      8 "Don't know"
      9 "Special answers"
  /M27     
      0 "No flag"
      1 "> interval"
      2 "> interval by 1 month"
      3 "> age at death"
      4 "During pregnancy in calendar"
  /M28     
      0 "No flag"
      1 "> interval"
      2 "> interval by 1 month"
      4 "During pregnancy in calendar"
  /M29     
      0 "No flag"
      1 "> interval"
      2 "> interval by 1 month"
      4 "During pregnancy in calendar"
  /M34     
      0 "Immediately"
    100 "Within first hour"
    101 "Hours: 1"
    199 "Hours: number missing"
    201 "Days: 1"
    299 "Days: number missing"
  /M35     
     96 "On demand"
  /M36     
     96 "On demand"
  /M38     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M39A    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M39     
      0 "None"
      7 "7+"
      8 "Don't know"
  /M42A    
      0 "No"
      1 "Yes"
  /M42B    
      0 "No"
      1 "Yes"
  /M42C    
      0 "No"
      1 "Yes"
  /M42D    
      0 "No"
      1 "Yes"
  /M42E    
      0 "No"
      1 "Yes"
  /M43     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M44     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M45     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M46     
      0 "Were not taken"
    998 "Don't know"
  /M47     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M48     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49A    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49C    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49D    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49E    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49F    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49G    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49X    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M49Z    
      0 "No"
      1 "Yes: don't know which drug taken"
      8 "Don't know"
  /M49Y    
      0 "No"
      1 "Yes, took no drug"
      8 "Don't know"
  /M50     
      0 "No"
      1 "Yes"
  /M51     
    100 "Zero hours"
    101 "1 Hours"
    199 "Hours missing"
    200 "0 Days"
    201 "1 Days"
    299 "Days missing"
    301 "1 Week"
    399 "Weeks missing"
    998 "Don't know"
  /M52     
     10 "HEALTH PROFESSIONAL"
     11 "Doctor"
     12 "Nurse/medical assistant"
     13 "Midwife"
     20 "OTHER PERSON"
     21 "Traditional healer"
     22 "Community health worker"
     23 "Community health mother and child"
     96 "Other"
  /M54     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M55A    
      0 "No"
      1 "Yes"
  /M55B    
      0 "No"
      1 "Yes"
  /M55C    
      0 "No"
      1 "Yes"
  /M55D    
      0 "No"
      1 "Yes"
  /M55E    
      0 "No"
      1 "Yes"
  /M55F    
      0 "No"
      1 "Yes"
  /M55G    
      0 "No"
      1 "Yes"
  /M55H    
      0 "No"
      1 "Yes"
  /M55I    
      0 "No"
      1 "Yes"
  /M55J    
      0 "No"
      1 "Yes"
  /M55K    
      0 "No"
      1 "Yes"
  /M55L    
      0 "No"
      1 "Yes"
  /M55M    
      0 "No"
      1 "Yes"
  /M55N    
      0 "No"
      1 "Yes"
  /M55O    
      0 "No"
      1 "Yes"
  /M55X    
      0 "No"
      1 "Yes"
  /M55Z    
      0 "No: given something"
      1 "Yes: given nothing"
  /M57A    
      0 "No"
      1 "Yes"
  /M57B    
      0 "No"
      1 "Yes"
  /M57C    
      0 "No"
      1 "Yes"
  /M57D    
      0 "No"
      1 "Yes"
  /M57E    
      0 "No"
      1 "Yes"
  /M57F    
      0 "No"
      1 "Yes"
  /M57G    
      0 "No"
      1 "Yes"
  /M57H    
      0 "No"
      1 "Yes"
  /M57I    
      0 "No"
      1 "Yes"
  /M57J    
      0 "No"
      1 "Yes"
  /M57K    
      0 "No"
      1 "Yes"
  /M57L    
      0 "No"
      1 "Yes"
  /M57M    
      0 "No"
      1 "Yes"
  /M57N    
      0 "No"
      1 "Yes"
  /M57O    
      0 "No"
      1 "Yes"
  /M57P    
      0 "No"
      1 "Yes"
  /M57Q    
      0 "No"
      1 "Yes"
  /M57R    
      0 "No"
      1 "Yes"
  /M57S    
      0 "No"
      1 "Yes"
  /M57T    
      0 "No"
      1 "Yes"
  /M57U    
      0 "No"
      1 "Yes"
  /M57V    
      0 "No"
      1 "Yes"
  /M57X    
      0 "No"
      1 "Yes"
  /M60     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M61     
    100 "Hours: 0"
    101 "Hours: 1"
    199 "Hours: number missing"
    201 "Days: 1"
    299 "Days: number missing"
    301 "Weeks: 1"
    399 "Weeks: number missing"
    998 "Don't know"
  /M62     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M65A    
      0 "No"
      1 "Yes"
  /M65B    
      0 "No"
      1 "Yes"
  /M65C    
      0 "No"
      1 "Yes"
  /M65D    
      0 "No"
      1 "Yes"
  /M65E    
      0 "No"
      1 "Yes"
  /M65F    
      0 "No"
      1 "Yes"
  /M65G    
      0 "No"
      1 "Yes"
  /M65H    
      0 "No"
      1 "Yes"
  /M65I    
      0 "No"
      1 "Yes"
  /M65J    
      0 "No"
      1 "Yes"
  /M65K    
      0 "No"
      1 "Yes"
  /M65L    
      0 "No"
      1 "Yes"
  /M65X    
      0 "No"
      1 "Yes"
  /M66     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M70     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /M71     
    100 "Immediately/in first hour"
    101 "Hours: 1"
    199 "Hours: number missing"
    201 "Days: 1"
    299 "Days: number missing"
    301 "Weeks: 1"
    399 "Weeks: number missing"
    998 "Don't know"
  /M72     
     10 "MEDICAL PERSONNEL"
     11 "Doctor"
     12 "Nurse, medical assistant"
     13 "Midwife"
     20 "OTHER PERSON"
     21 "Traditional healer"
     22 "Community health worker"
     23 "Community health mother and child"
     96 "Other"
  /M73     
     10 "HOME"
     11 "Respondent's home"
     12 "Other home"
     20 "PUBLIC SECTOR"
     21 "Referral hospital"
     22 "Health center"
     23 "Health post"
     24 "Provincial / District hospital"
     26 "Other public sector"
     30 "PRIVATE SECTOR"
     31 "Private hospital, clinic"
     32 "Polyclinic"
     33 "Dispensary"
     36 "Other private sector"
     96 "Other"
  /H1      
      0 "No card"
      1 "Yes, seen"
      2 "Yes, not seen"
      3 "No longer has card"
  /H2      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H2D     
     97 "Inconsistent"
     98 "Don't know"
  /H2M     
     97 "Inconsistent"
     98 "Don't know"
  /H2Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H3      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H3D     
     97 "Inconsistent"
     98 "Don't know"
  /H3M     
     97 "Inconsistent"
     98 "Don't know"
  /H3Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H4      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H4D     
     97 "Inconsistent"
     98 "Don't know"
  /H4M     
     97 "Inconsistent"
     98 "Don't know"
  /H4Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H5      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H5D     
     97 "Inconsistent"
     98 "Don't know"
  /H5M     
     97 "Inconsistent"
     98 "Don't know"
  /H5Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H6      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H6D     
     97 "Inconsistent"
     98 "Don't know"
  /H6M     
     97 "Inconsistent"
     98 "Don't know"
  /H6Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H7      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H7D     
     97 "Inconsistent"
     98 "Don't know"
  /H7M     
     97 "Inconsistent"
     98 "Don't know"
  /H7Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H8      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H8D     
     97 "Inconsistent"
     98 "Don't know"
  /H8M     
     97 "Inconsistent"
     98 "Don't know"
  /H8Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H9      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H9D     
     97 "Inconsistent"
     98 "Don't know"
  /H9M     
     97 "Inconsistent"
     98 "Don't know"
  /H9Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H0      
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H0D     
     97 "Inconsistent"
     98 "Don't know"
  /H0M     
     97 "Inconsistent"
     98 "Don't know"
  /H0Y     
   9997 "Inconsistent"
   9998 "Don't know"
  /H10     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H11     
      0 "No"
      1 "Yes, last 24 hours"
      2 "Yes, last two weeks"
      8 "Don't know"
  /H11B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H12A    
      0 "No"
      1 "Yes"
  /H12B    
      0 "No"
      1 "Yes"
  /H12C    
      0 "No"
      1 "Yes"
  /H12D    
      0 "No"
      1 "Yes"
  /H12E    
      0 "No"
      1 "Yes"
  /H12F    
      0 "No"
      1 "Yes"
  /H12G    
      0 "No"
      1 "Yes"
  /H12H    
      0 "No"
      1 "Yes"
  /H12I    
      0 "No"
      1 "Yes"
  /H12J    
      0 "No"
      1 "Yes"
  /H12K    
      0 "No"
      1 "Yes"
  /H12L    
      0 "No"
      1 "Yes"
  /H12M    
      0 "No"
      1 "Yes"
  /H12N    
      0 "No"
      1 "Yes"
  /H12O    
      0 "No"
      1 "Yes"
  /H12P    
      0 "No"
      1 "Yes"
  /H12Q    
      0 "No"
      1 "Yes"
  /H12R    
      0 "No"
      1 "Yes"
  /H12S    
      0 "No"
      1 "Yes"
  /H12T    
      0 "No"
      1 "Yes"
  /H12U    
      0 "No"
      1 "Yes"
  /H12V    
      0 "No"
      1 "Yes"
  /H12W    
      0 "No"
      1 "Yes"
  /H12X    
      0 "No"
      1 "Yes"
  /H12Y    
      0 "No: received treatment"
      1 "Yes: no treatment"
  /H12Z    
      0 "No"
      1 "Yes"
  /H13     
      0 "No"
      1 "Yes: ORS - spontaneous"
      2 "Yes: ORS - probed"
      8 "Don't know"
  /H13B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H14     
      0 "No"
      1 "Yes: RHS - spontaneous"
      2 "Yes: RHS - probed"
      8 "Don't know"
  /H15     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15A    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15C    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15D    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15E    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15F    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15G    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15H    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15I    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15J    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15K    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15L    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H15M    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H20     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H21A    
      0 "No: received treatment"
      1 "Yes: no treatment"
      8 "Don't know"
  /H21     
      0 "No"
      1 "Yes"
  /H22     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H31     
      0 "No"
      1 "Yes, last 24 hours"
      2 "Yes, last two weeks"
      8 "Don't know"
  /H31B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H31C    
      1 "Chest only"
      2 "Nose only"
      3 "Both"
      6 "Other"
      8 "Don't know"
  /H31D    
      0 "Nothing to drink"
      2 "Much less"
      3 "Somewhat less"
      4 "About the same"
      5 "More"
      8 "Don't know"
  /H31E    
      0 "Stopped food"
      1 "Never gave food"
      2 "Much less"
      3 "Somewhat less"
      4 "About the same"
      5 "More"
      8 "Don't know"
  /H32A    
      0 "No"
      1 "Yes"
  /H32B    
      0 "No"
      1 "Yes"
  /H32C    
      0 "No"
      1 "Yes"
  /H32D    
      0 "No"
      1 "Yes"
  /H32E    
      0 "No"
      1 "Yes"
  /H32F    
      0 "No"
      1 "Yes"
  /H32G    
      0 "No"
      1 "Yes"
  /H32H    
      0 "No"
      1 "Yes"
  /H32I    
      0 "No"
      1 "Yes"
  /H32J    
      0 "No"
      1 "Yes"
  /H32K    
      0 "No"
      1 "Yes"
  /H32L    
      0 "No"
      1 "Yes"
  /H32M    
      0 "No"
      1 "Yes"
  /H32N    
      0 "No"
      1 "Yes"
  /H32O    
      0 "No"
      1 "Yes"
  /H32P    
      0 "No"
      1 "Yes"
  /H32Q    
      0 "No"
      1 "Yes"
  /H32R    
      0 "No"
      1 "Yes"
  /H32S    
      0 "No"
      1 "Yes"
  /H32T    
      0 "No"
      1 "Yes"
  /H32U    
      0 "No"
      1 "Yes"
  /H32V    
      0 "No"
      1 "Yes"
  /H32W    
      0 "No"
      1 "Yes"
  /H32X    
      0 "No"
      1 "Yes"
  /H32Y    
      0 "No: received treatment"
      1 "Yes: no treatment"
  /H32Z    
      0 "No"
      1 "Yes"
  /H33     
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H33D    
     97 "Inconsistent"
     98 "Don't know"
  /H33M    
     97 "Inconsistent"
     98 "Don't know"
  /H33Y    
   9997 "Inconsistent"
   9998 "Don't know"
  /H34     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H35     
      0 "No"
      1 "Yes"
      2 "No vaccination in last 2 years"
      8 "Don't know"
  /H36A    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H36B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H36C    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H36D    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H36E    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H36F    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H37A    
      0 "No"
      1 "Yes"
  /H37B    
      0 "No"
      1 "Yes"
  /H37C    
      0 "No"
      1 "Yes"
  /H37D    
      0 "No"
      1 "Yes"
  /H37E    
      0 "No"
      1 "Yes"
  /H37F    
      0 "No"
      1 "Yes"
  /H37G    
      0 "No"
      1 "Yes"
  /H37H    
      0 "No"
      1 "Yes"
  /H37I    
      0 "No"
      1 "Yes"
  /H37J    
      0 "No"
      1 "Yes"
  /H37K    
      0 "No"
      1 "Yes"
  /H37L    
      0 "No"
      1 "Yes"
  /H37M    
      0 "No"
      1 "Yes"
  /H37N    
      0 "No"
      1 "Yes"
  /H37O    
      0 "No"
      1 "Yes"
  /H37P    
      0 "No"
      1 "Yes"
  /H37X    
      0 "No"
      1 "Yes"
  /H37Y    
      0 "No"
      1 "Yes, nothing taken"
  /H37Z    
      0 "No"
      1 "Yes, don't know"
  /H38     
      0 "Nothing to drink"
      2 "Much less"
      3 "Somewhat less"
      4 "About the same"
      5 "More"
      8 "Don't know"
  /H39     
      0 "Stopped food"
      1 "Never gave food"
      2 "Much less"
      3 "Somewhat less"
      4 "About the same"
      5 "More"
      8 "Don't know"
  /H40     
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /H40D    
     97 "Inconsistent"
     98 "Don't know"
  /H40M    
     97 "Inconsistent"
     98 "Don't know"
  /H40Y    
   9997 "Inconsistent"
   9998 "Don't know"
  /H41A    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H41B    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H42     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H43     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H44A    
     10 "PUBLIC SECTOR"
     11 "Referral hospital"
     12 "District hospital"
     13 "Health center"
     14 "Health post"
     15 "Outreach"
     16 "Community health worker"
     17 "Other public"
     20 "PRIVATE SECTOR"
     21 "Polyclinic"
     22 "Clinic"
     23 "Dispensary"
     24 "Pharmacy"
     25 "Other private"
     30 "OTHER"
     31 "Kiosk"
     32 "Traditional healer"
     33 "Church"
     34 "Friend/relative"
     96 "Other"
  /H44B    
      0 "Same day"
     98 "Don't know"
  /H44C    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /H45     
     98 "Don't know"
  /H46A    
     10 "PUBLIC SECTOR"
     11 "Referral hospital"
     12 "District hospital"
     13 "Health center"
     14 "Health post"
     15 "Outreach"
     16 "Community health worker"
     17 "Other public"
     20 "PRIVATE SECTOR"
     21 "Polyclinic"
     22 "Clinic"
     23 "Dispensary"
     24 "Pharmacy"
     25 "Other private"
     30 "OTHER"
     31 "Kiosk"
     32 "Traditional healer"
     33 "Church"
     34 "Friend/relative"
     96 "Other"
  /H46B    
      0 "Same day"
     98 "Don't know"
  /H47     
      0 "No"
      1 "Yes"
      8 "Don't know"
  /HW2     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HW3     
   9994 "Not present"
   9995 "Refused"
   9996 "Other"
  /HW4     
   9998 "Flagged cases"
  /HW5     
   9998 "Flagged cases"
  /HW6     
   99998 "Flagged cases"
  /HW7     
   9998 "Flagged cases"
  /HW8     
   9998 "Flagged cases"
  /HW9     
   99998 "Flagged cases"
  /HW10    
   9998 "Flagged cases"
  /HW11    
   9998 "Flagged cases"
  /HW12    
   99998 "Flagged cases"
  /HW13    
      0 "Measured"
      1 "Dead"
      2 "Sick"
      3 "Not present"
      4 "Refused"
      5 "Mother refused"
      6 "Other"
      7 "No measurement found in household"
  /HW15    
      0 "Not measured"
      1 "Lying"
      2 "Standing"
      3 "Not Measured"
  /HW16    
     97 "Inconsistent"
     98 "Don't know"
  /HW51    
      0 "Not in household"
  /HW52    
      1 "Granted"
      2 "Refused"
  /HW53    
    994 "Not present"
    995 "Refused"
    996 "Other"
  /HW55    
      0 "Measured"
      1 "Dead"
      3 "Not present"
      4 "Refused"
      6 "Other"
      7 "No measurement found in household"
  /HW56    
    997 "Inconsistent"
  /HW57    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
  /HW58    
      0 "No"
      1 "Yes"
  /HW70    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HW71    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HW72    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /HW73    
   9996 "Height out of plausible limits"
   9997 "Age in days out of plausible limits"
   9998 "Flagged cases"
  /ML0     
      0 "No net"
      1 "Only treated nets"
      2 "Both treated and untreated nets"
      3 "Only untreated nets"
  /ML1     
     98 "Don't know"
  /ML2     
      1 "Antenatal visit"
      2 "Another facility visit"
      6 "Other source"
  /ML11    
      0 "No"
      1 "Yes, fever only"
      2 "Yes, cough only"
      3 "Both fever and cough"
      8 "Don't know"
  /ML12    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /ML13A   
      0 "No"
      1 "Yes"
  /ML13B   
      0 "No"
      1 "Yes"
  /ML13C   
      0 "No"
      1 "Yes"
  /ML13D   
      0 "No"
      1 "Yes"
  /ML13E   
      0 "No"
      1 "Yes"
  /ML13F   
      0 "No"
      1 "Yes"
  /ML13G   
      0 "No"
      1 "Yes"
  /ML13H   
      0 "No"
      1 "Yes"
  /ML13I   
      0 "No"
      1 "Yes"
  /ML13J   
      0 "No"
      1 "Yes"
  /ML13K   
      0 "No"
      1 "Yes"
  /ML13L   
      0 "No"
      1 "Yes"
  /ML13M   
      0 "No"
      1 "Yes"
  /ML13N   
      0 "No"
      1 "Yes"
  /ML13O   
      0 "No"
      1 "Yes"
  /ML13P   
      0 "No"
      1 "Yes"
  /ML13X   
      0 "No"
      1 "Yes"
  /ML13Y   
      0 "No"
      1 "Yes, nothing taken"
  /ML13Z   
      0 "No"
      1 "Yes, don't know"
  /ML14A   
      0 "No"
      1 "Yes"
  /ML14B   
      0 "No"
      1 "Yes"
  /ML14Y   
      0 "No"
      1 "Yes"
  /ML14Z   
      0 "No"
      1 "Yes"
  /ML15A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML15B   
      7 "7+ days"
      8 "Don't know"
  /ML15C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML16A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML16B   
      7 "7+ days"
      8 "Don't know"
  /ML16C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML17A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML17B   
      7 "7+ days"
      8 "Don't know"
  /ML17C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML18A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML18B   
      7 "7+ days"
      8 "Don't know"
  /ML18C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML19A   
      0 "No"
      1 "Yes"
  /ML19B   
      0 "No"
      1 "Yes"
  /ML19C   
      0 "No"
      1 "Yes"
  /ML19D   
      0 "No"
      1 "Yes"
  /ML19E   
      0 "No"
      1 "Yes"
  /ML19F   
      0 "No"
      1 "Yes"
  /ML19X   
      0 "No"
      1 "Yes"
  /ML19Y   
      0 "No"
      1 "Yes"
  /ML19Z   
      0 "No"
      1 "Yes"
  /ML20A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML20B   
      7 "7+ days"
      8 "Don't know"
  /ML20C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML21A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML21B   
      7 "7+ days"
      8 "Don't know"
  /ML21C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML22A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML22B   
      7 "7+ days"
      8 "Don't know"
  /ML22C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML23A   
      0 "Same day as fever/cough"
      1 "Next day"
      2 "2 days after"
      3 "3 days after"
      4 "4+ days after"
      8 "Don't know"
  /ML23B   
      7 "7+ days"
      8 "Don't know"
  /ML23C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /ML24C   
      0 "Other source"
      1 "At home"
      8 "Don't know"
  /SLANG   
      1 "Kinyarwanda"
      6 "Other"
  /STRANS  
      0 "No"
      1 "Yes"
      9 "Missing"
  /SDISTRICT
     11 "Nyarugenge"
     12 "Gasabo"
     13 "Kicukiro"
     21 "Nyanza"
     22 "Gisagara"
     23 "Nyaruguru"
     24 "Huye"
     25 "Nyamagabe"
     26 "Ruhango"
     27 "Muhanga"
     28 "Kamonyi"
     31 "Karongi"
     32 "Rutsiro"
     33 "Rubavu"
     34 "Nyabihu"
     35 "Ngororero"
     36 "Rusizi"
     37 "Nyamasheke"
     41 "Rulindo"
     42 "Gakenke"
     43 "Musanze"
     44 "Burera"
     45 "Gicumbi"
     51 "Rwamagana"
     52 "Nyagatare"
     53 "Gatsibo"
     54 "Kayonza"
     55 "Kirehe"
     56 "Ngoma"
     57 "Bugesera"
  /S105    
      1 "Primary"
      2 "Post-primary/vocational"
      3 "Secondary"
      4 "Tertiary"
      6 "Pre-primary"
  /S106A   
      0 "No education"
      1 "Primary"
      2 "Secondary or higher"
  /S115    
      0 "None"
  /S205CA  
      0 "No"
      1 "Yes"
  /S205CB  
      0 "No"
      1 "Yes"
  /S205CC  
      0 "No"
      1 "Yes"
  /S205CD  
      0 "No"
      1 "Yes"
  /S205CE  
      0 "No"
      1 "Yes"
  /S205CX  
      0 "No"
      1 "Yes"
  /S205CZ  
      0 "No"
      1 "Yes - don't know"
  /S564    
      0 "Not in household"
  /S564A   
      0 "Not in household"
  /S566    
     10 "10 or more"
  /S567A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S567B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S567C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S568A   
      8 "Don't know"
  /S568B   
      8 "Don't know"
  /S570    
      0 "Not in household"
  /S570A   
      0 "Not in household"
  /S572    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S573    
     95 "95+"
     98 "Don't know"
  /S574AA  
      0 "No"
      1 "Yes"
  /S574AB  
      0 "No"
      1 "Yes"
  /S574AX  
      0 "No"
      1 "Yes"
  /S574AY  
      0 "No"
      1 "Yes"
  /S574BA  
      0 "No"
      1 "Yes"
  /S574BB  
      0 "No"
      1 "Yes"
  /S574BX  
      0 "No"
      1 "Yes"
  /S574BY  
      0 "No"
      1 "Yes"
  /S574CA  
      0 "No"
      1 "Yes"
  /S574CB  
      0 "No"
      1 "Yes"
  /S574CX  
      0 "No"
      1 "Yes"
  /S574CY  
      0 "No"
      1 "Yes"
  /S574DA  
      0 "No"
      1 "Yes"
  /S574DB  
      0 "No"
      1 "Yes"
  /S574DX  
      0 "No"
      1 "Yes"
  /S574DY  
      0 "No"
      1 "Yes"
  /S574EA  
      0 "No"
      1 "Yes"
  /S574EB  
      0 "No"
      1 "Yes"
  /S574EX  
      0 "No"
      1 "Yes"
  /S574EY  
      0 "No"
      1 "Yes"
  /S574FA  
      0 "No"
      1 "Yes"
  /S574FB  
      0 "No"
      1 "Yes"
  /S574FX  
      0 "No"
      1 "Yes"
  /S574FY  
      0 "No"
      1 "Yes"
  /S575    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S576    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S577    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S578    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S579    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S580    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S581    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S582    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S583    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S584    
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S623A   
     95 "95+"
  /S623B   
     95 "95+"
  /S623C   
     95 "95+"
  /S626A   
     95 "95+"
  /S714D   
      0 "No"
      1 "Yes"
  /S826E   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S827A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S827B   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S827C   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S907A   
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S910B   
      0 "No"
      1 "Yes"
  /S910D   
      0 "No"
      1 "Yes"
  /S910E   
      0 "No"
      1 "Yes"
  /S1011A  
      0 "No"
      1 "Yes, two weeks or longer"
      2 "Yes, less than two weeks"
  /S1011B  
      0 "No"
      1 "Yes, one month or longer"
      2 "Yes, less than one month"
  /S1011C  
      0 "No"
      1 "Yes, one month or longer"
      2 "Yes, less than one month"
  /S1011D  
      0 "No"
      1 "Yes, one month or longer"
      2 "Yes, less than one month"
  /S1011E  
      0 "No"
      1 "Yes, one month or longer"
      2 "Yes, less than one month"
  /S1011F  
      0 "No"
      1 "Yes, one month or longer"
      2 "Yes, less than one month"
  /S1013   
      0 "No"
      1 "Yes"
  /S1014A  
      0 "No"
      1 "Yes"
  /S1014B  
      0 "No"
      1 "Yes"
  /S1014C  
      0 "No"
      1 "Yes"
  /S1014D  
      0 "No"
      1 "Yes"
  /S1014E  
      0 "No"
      1 "Yes"
  /S1014F  
      0 "No"
      1 "Yes"
  /S1014I  
      0 "No"
      1 "Yes"
  /S1014J  
      0 "No"
      1 "Yes"
  /S1014K  
      0 "No"
      1 "Yes"
  /S1014M  
      0 "No"
      1 "Yes"
  /S1014N  
      0 "No"
      1 "Yes"
  /S1014O  
      0 "No"
      1 "Yes"
  /S1014P  
      0 "No"
      1 "Yes"
  /S1014S  
      0 "No"
      1 "Yes"
  /S1014T  
      0 "No"
      1 "Yes"
  /S1014V  
      0 "No"
      1 "Yes"
  /S1014X  
      0 "No"
      1 "Yes"
  /SDV18   
      1 "Yes"
      2 "No"
  /SDV18C  
      1 "Mother/Step-mother"
      2 "Father/Step-father"
      3 "Sister/Brother"
      4 "Daughter/Son"
      5 "Other relative"
      6 "Current girlfriend"
      7 "Former girlfriend"
      8 "Mother-in-law"
      9 "Father-in-law"
     10 "Other in-law"
     11 "Teacher"
     12 "Employer/Someone at work"
     13 "Police/Soldier"
     96 "Other"
  /SDV24   
      1 "Yes"
      2 "No"
  /SDV24A  
      3 "Current/Former boyfriend"
      4 "Father/Step-father"
      5 "Brother/Step-brother"
      6 "Other relative"
      7 "In-law"
      8 "Own friend/Acquaintance"
      9 "Family friend"
     10 "Teacher"
     11 "Employer/Someone at work"
     12 "Police/Soldier"
     13 "Priest/Religious leader"
     14 "Stranger"
     15 "Neighbor"
     96 "Other"
     99 "Missing"
  /S412B   
     98 "Don't know"
  /S412D   
     98 "Don't know"
  /S412F   
     98 "Don't know"
  /S425AA  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AB  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AC  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AD  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AE  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AF  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AI  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AJ  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AK  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AM  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AN  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AP  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AS  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AT  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AU  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AV  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S425AX  
      0 "No"
      1 "Yes"
      8 "Don't know"
  /S435A   
      1 "Ambulance"
      2 "Private car"
      3 "Motorcycle"
      4 "Walk"
      6 "Other"
  /S452U   
      1 "Days"
      2 "Months"
      9 "Special answers"
  /S452N   
     98 "Don't know"
  /S460B   
      1 "Facility cost too much"
      2 "Too far/no transport"
      3 "Don't trust facility"
      4 "No female provider"
      5 "Husband/family did not allow"
      6 "Not necessary"
      7 "Not customary"
      8 "Delivered on the way"
     96 "Other"
  /S506N1  
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /S506N1D 
     97 "Inconsistent"
     98 "Don't know"
  /S506N1M 
     97 "Inconsistent"
     98 "Don't know"
  /S506N1Y 
   9997 "Inconsistent"
   9998 "Don't know"
  /S506N2  
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /S506N2D 
     97 "Inconsistent"
     98 "Don't know"
  /S506N2M 
     97 "Inconsistent"
     98 "Don't know"
  /S506N2Y 
   9997 "Inconsistent"
   9998 "Don't know"
  /S506N3  
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /S506N3D 
     97 "Inconsistent"
     98 "Don't know"
  /S506N3M 
     97 "Inconsistent"
     98 "Don't know"
  /S506N3Y 
   9997 "Inconsistent"
   9998 "Don't know"
  /S506R1  
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /S506R1D 
     97 "Inconsistent"
     98 "Don't know"
  /S506R1M 
     97 "Inconsistent"
     98 "Don't know"
  /S506R1Y 
   9997 "Inconsistent"
   9998 "Don't know"
  /S506R2  
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /S506R2D 
     97 "Inconsistent"
     98 "Don't know"
  /S506R2M 
     97 "Inconsistent"
     98 "Don't know"
  /S506R2Y 
   9997 "Inconsistent"
   9998 "Don't know"
  /S506R3  
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /S506R3D 
     97 "Inconsistent"
     98 "Don't know"
  /S506R3M 
     97 "Inconsistent"
     98 "Don't know"
  /S506R3Y 
   9997 "Inconsistent"
   9998 "Don't know"
  /S506MR  
      0 "No"
      1 "Vaccination date on card"
      2 "Reported by mother"
      3 "Vaccination marked on card"
      8 "Don't know"
  /S506MRD 
     97 "Inconsistent"
     98 "Don't know"
  /S506MRM 
     97 "Inconsistent"
     98 "Don't know"
  /S506MRY 
   9997 "Inconsistent"
   9998 "Don't know"
  /S517B   
      1 "Yes"
      2 "No"
  /S561A   
      0 "No"
      1 "Yes"
  /S561BA  
      0 "No"
      1 "Yes"
  /S561BB  
      0 "No"
      1 "Yes"
  /S561BC  
      0 "No"
      1 "Yes"
  /S561BD  
      0 "No"
      1 "Yes"
  /S561BX  
      0 "No"
      1 "Yes"
 .
 EXECUTE.
SAVE OUTFILE='C:\COUNTRIES\RW70\RWKR70FL.sav'.
